// Code generated by ent, DO NOT EDIT.

package serviceaccountkeypair

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/grokify/coreforge/identity/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLTE(FieldID, id))
}

// ServiceAccountID applies equality check predicate on the "service_account_id" field. It's identical to ServiceAccountIDEQ.
func ServiceAccountID(v uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldServiceAccountID, v))
}

// KeyID applies equality check predicate on the "key_id" field. It's identical to KeyIDEQ.
func KeyID(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldKeyID, v))
}

// PublicKeyPem applies equality check predicate on the "public_key_pem" field. It's identical to PublicKeyPemEQ.
func PublicKeyPem(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldPublicKeyPem, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldExpiresAt, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldActive, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldLastUsedAt, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldRevoked, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldCreatedAt, v))
}

// ServiceAccountIDEQ applies the EQ predicate on the "service_account_id" field.
func ServiceAccountIDEQ(v uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldServiceAccountID, v))
}

// ServiceAccountIDNEQ applies the NEQ predicate on the "service_account_id" field.
func ServiceAccountIDNEQ(v uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldServiceAccountID, v))
}

// ServiceAccountIDIn applies the In predicate on the "service_account_id" field.
func ServiceAccountIDIn(vs ...uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldServiceAccountID, vs...))
}

// ServiceAccountIDNotIn applies the NotIn predicate on the "service_account_id" field.
func ServiceAccountIDNotIn(vs ...uuid.UUID) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldServiceAccountID, vs...))
}

// KeyIDEQ applies the EQ predicate on the "key_id" field.
func KeyIDEQ(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldKeyID, v))
}

// KeyIDNEQ applies the NEQ predicate on the "key_id" field.
func KeyIDNEQ(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldKeyID, v))
}

// KeyIDIn applies the In predicate on the "key_id" field.
func KeyIDIn(vs ...string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldKeyID, vs...))
}

// KeyIDNotIn applies the NotIn predicate on the "key_id" field.
func KeyIDNotIn(vs ...string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldKeyID, vs...))
}

// KeyIDGT applies the GT predicate on the "key_id" field.
func KeyIDGT(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGT(FieldKeyID, v))
}

// KeyIDGTE applies the GTE predicate on the "key_id" field.
func KeyIDGTE(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGTE(FieldKeyID, v))
}

// KeyIDLT applies the LT predicate on the "key_id" field.
func KeyIDLT(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLT(FieldKeyID, v))
}

// KeyIDLTE applies the LTE predicate on the "key_id" field.
func KeyIDLTE(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLTE(FieldKeyID, v))
}

// KeyIDContains applies the Contains predicate on the "key_id" field.
func KeyIDContains(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldContains(FieldKeyID, v))
}

// KeyIDHasPrefix applies the HasPrefix predicate on the "key_id" field.
func KeyIDHasPrefix(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldHasPrefix(FieldKeyID, v))
}

// KeyIDHasSuffix applies the HasSuffix predicate on the "key_id" field.
func KeyIDHasSuffix(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldHasSuffix(FieldKeyID, v))
}

// KeyIDEqualFold applies the EqualFold predicate on the "key_id" field.
func KeyIDEqualFold(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEqualFold(FieldKeyID, v))
}

// KeyIDContainsFold applies the ContainsFold predicate on the "key_id" field.
func KeyIDContainsFold(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldContainsFold(FieldKeyID, v))
}

// KeyTypeEQ applies the EQ predicate on the "key_type" field.
func KeyTypeEQ(v KeyType) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldKeyType, v))
}

// KeyTypeNEQ applies the NEQ predicate on the "key_type" field.
func KeyTypeNEQ(v KeyType) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldKeyType, v))
}

// KeyTypeIn applies the In predicate on the "key_type" field.
func KeyTypeIn(vs ...KeyType) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldKeyType, vs...))
}

// KeyTypeNotIn applies the NotIn predicate on the "key_type" field.
func KeyTypeNotIn(vs ...KeyType) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldKeyType, vs...))
}

// AlgorithmEQ applies the EQ predicate on the "algorithm" field.
func AlgorithmEQ(v Algorithm) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldAlgorithm, v))
}

// AlgorithmNEQ applies the NEQ predicate on the "algorithm" field.
func AlgorithmNEQ(v Algorithm) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldAlgorithm, v))
}

// AlgorithmIn applies the In predicate on the "algorithm" field.
func AlgorithmIn(vs ...Algorithm) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldAlgorithm, vs...))
}

// AlgorithmNotIn applies the NotIn predicate on the "algorithm" field.
func AlgorithmNotIn(vs ...Algorithm) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldAlgorithm, vs...))
}

// PublicKeyPemEQ applies the EQ predicate on the "public_key_pem" field.
func PublicKeyPemEQ(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldPublicKeyPem, v))
}

// PublicKeyPemNEQ applies the NEQ predicate on the "public_key_pem" field.
func PublicKeyPemNEQ(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldPublicKeyPem, v))
}

// PublicKeyPemIn applies the In predicate on the "public_key_pem" field.
func PublicKeyPemIn(vs ...string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldPublicKeyPem, vs...))
}

// PublicKeyPemNotIn applies the NotIn predicate on the "public_key_pem" field.
func PublicKeyPemNotIn(vs ...string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldPublicKeyPem, vs...))
}

// PublicKeyPemGT applies the GT predicate on the "public_key_pem" field.
func PublicKeyPemGT(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGT(FieldPublicKeyPem, v))
}

// PublicKeyPemGTE applies the GTE predicate on the "public_key_pem" field.
func PublicKeyPemGTE(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGTE(FieldPublicKeyPem, v))
}

// PublicKeyPemLT applies the LT predicate on the "public_key_pem" field.
func PublicKeyPemLT(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLT(FieldPublicKeyPem, v))
}

// PublicKeyPemLTE applies the LTE predicate on the "public_key_pem" field.
func PublicKeyPemLTE(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLTE(FieldPublicKeyPem, v))
}

// PublicKeyPemContains applies the Contains predicate on the "public_key_pem" field.
func PublicKeyPemContains(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldContains(FieldPublicKeyPem, v))
}

// PublicKeyPemHasPrefix applies the HasPrefix predicate on the "public_key_pem" field.
func PublicKeyPemHasPrefix(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldHasPrefix(FieldPublicKeyPem, v))
}

// PublicKeyPemHasSuffix applies the HasSuffix predicate on the "public_key_pem" field.
func PublicKeyPemHasSuffix(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldHasSuffix(FieldPublicKeyPem, v))
}

// PublicKeyPemEqualFold applies the EqualFold predicate on the "public_key_pem" field.
func PublicKeyPemEqualFold(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEqualFold(FieldPublicKeyPem, v))
}

// PublicKeyPemContainsFold applies the ContainsFold predicate on the "public_key_pem" field.
func PublicKeyPemContainsFold(v string) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldContainsFold(FieldPublicKeyPem, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotNull(FieldExpiresAt))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldActive, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotNull(FieldLastUsedAt))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldRevoked, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotNull(FieldRevokedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.FieldLTE(FieldCreatedAt, v))
}

// HasServiceAccount applies the HasEdge predicate on the "service_account" edge.
func HasServiceAccount() predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServiceAccountTable, ServiceAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServiceAccountWith applies the HasEdge predicate on the "service_account" edge with a given conditions (other predicates).
func HasServiceAccountWith(preds ...predicate.ServiceAccount) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(func(s *sql.Selector) {
		step := newServiceAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServiceAccountKeyPair) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServiceAccountKeyPair) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServiceAccountKeyPair) predicate.ServiceAccountKeyPair {
	return predicate.ServiceAccountKeyPair(sql.NotPredicates(p))
}
