// Code generated by ent, DO NOT EDIT.

package application

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/grokify/systemforge/identity/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldUpdatedAt, v))
}

// PrincipalID applies equality check predicate on the "principal_id" field. It's identical to PrincipalIDEQ.
func PrincipalID(v uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldPrincipalID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldClientID, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldDescription, v))
}

// LogoURL applies equality check predicate on the "logo_url" field. It's identical to LogoURLEQ.
func LogoURL(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldLogoURL, v))
}

// AccessTokenTTL applies equality check predicate on the "access_token_ttl" field. It's identical to AccessTokenTTLEQ.
func AccessTokenTTL(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldAccessTokenTTL, v))
}

// RefreshTokenTTL applies equality check predicate on the "refresh_token_ttl" field. It's identical to RefreshTokenTTLEQ.
func RefreshTokenTTL(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldRefreshTokenTTL, v))
}

// RefreshTokenRotation applies equality check predicate on the "refresh_token_rotation" field. It's identical to RefreshTokenRotationEQ.
func RefreshTokenRotation(v bool) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldRefreshTokenRotation, v))
}

// FirstParty applies equality check predicate on the "first_party" field. It's identical to FirstPartyEQ.
func FirstParty(v bool) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldFirstParty, v))
}

// Public applies equality check predicate on the "public" field. It's identical to PublicEQ.
func Public(v bool) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldPublic, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldUpdatedAt, v))
}

// PrincipalIDEQ applies the EQ predicate on the "principal_id" field.
func PrincipalIDEQ(v uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldPrincipalID, v))
}

// PrincipalIDNEQ applies the NEQ predicate on the "principal_id" field.
func PrincipalIDNEQ(v uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldPrincipalID, v))
}

// PrincipalIDIn applies the In predicate on the "principal_id" field.
func PrincipalIDIn(vs ...uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldPrincipalID, vs...))
}

// PrincipalIDNotIn applies the NotIn predicate on the "principal_id" field.
func PrincipalIDNotIn(vs ...uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldPrincipalID, vs...))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.Application {
	return predicate.Application(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.Application {
	return predicate.Application(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.Application {
	return predicate.Application(sql.FieldContainsFold(FieldClientID, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Application {
	return predicate.Application(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Application {
	return predicate.Application(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Application {
	return predicate.Application(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Application {
	return predicate.Application(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Application {
	return predicate.Application(sql.FieldContainsFold(FieldDescription, v))
}

// LogoURLEQ applies the EQ predicate on the "logo_url" field.
func LogoURLEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldLogoURL, v))
}

// LogoURLNEQ applies the NEQ predicate on the "logo_url" field.
func LogoURLNEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldLogoURL, v))
}

// LogoURLIn applies the In predicate on the "logo_url" field.
func LogoURLIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldLogoURL, vs...))
}

// LogoURLNotIn applies the NotIn predicate on the "logo_url" field.
func LogoURLNotIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldLogoURL, vs...))
}

// LogoURLGT applies the GT predicate on the "logo_url" field.
func LogoURLGT(v string) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldLogoURL, v))
}

// LogoURLGTE applies the GTE predicate on the "logo_url" field.
func LogoURLGTE(v string) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldLogoURL, v))
}

// LogoURLLT applies the LT predicate on the "logo_url" field.
func LogoURLLT(v string) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldLogoURL, v))
}

// LogoURLLTE applies the LTE predicate on the "logo_url" field.
func LogoURLLTE(v string) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldLogoURL, v))
}

// LogoURLContains applies the Contains predicate on the "logo_url" field.
func LogoURLContains(v string) predicate.Application {
	return predicate.Application(sql.FieldContains(FieldLogoURL, v))
}

// LogoURLHasPrefix applies the HasPrefix predicate on the "logo_url" field.
func LogoURLHasPrefix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasPrefix(FieldLogoURL, v))
}

// LogoURLHasSuffix applies the HasSuffix predicate on the "logo_url" field.
func LogoURLHasSuffix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasSuffix(FieldLogoURL, v))
}

// LogoURLIsNil applies the IsNil predicate on the "logo_url" field.
func LogoURLIsNil() predicate.Application {
	return predicate.Application(sql.FieldIsNull(FieldLogoURL))
}

// LogoURLNotNil applies the NotNil predicate on the "logo_url" field.
func LogoURLNotNil() predicate.Application {
	return predicate.Application(sql.FieldNotNull(FieldLogoURL))
}

// LogoURLEqualFold applies the EqualFold predicate on the "logo_url" field.
func LogoURLEqualFold(v string) predicate.Application {
	return predicate.Application(sql.FieldEqualFold(FieldLogoURL, v))
}

// LogoURLContainsFold applies the ContainsFold predicate on the "logo_url" field.
func LogoURLContainsFold(v string) predicate.Application {
	return predicate.Application(sql.FieldContainsFold(FieldLogoURL, v))
}

// AppTypeEQ applies the EQ predicate on the "app_type" field.
func AppTypeEQ(v AppType) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldAppType, v))
}

// AppTypeNEQ applies the NEQ predicate on the "app_type" field.
func AppTypeNEQ(v AppType) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldAppType, v))
}

// AppTypeIn applies the In predicate on the "app_type" field.
func AppTypeIn(vs ...AppType) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldAppType, vs...))
}

// AppTypeNotIn applies the NotIn predicate on the "app_type" field.
func AppTypeNotIn(vs ...AppType) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldAppType, vs...))
}

// AccessTokenTTLEQ applies the EQ predicate on the "access_token_ttl" field.
func AccessTokenTTLEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldAccessTokenTTL, v))
}

// AccessTokenTTLNEQ applies the NEQ predicate on the "access_token_ttl" field.
func AccessTokenTTLNEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldAccessTokenTTL, v))
}

// AccessTokenTTLIn applies the In predicate on the "access_token_ttl" field.
func AccessTokenTTLIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldAccessTokenTTL, vs...))
}

// AccessTokenTTLNotIn applies the NotIn predicate on the "access_token_ttl" field.
func AccessTokenTTLNotIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldAccessTokenTTL, vs...))
}

// AccessTokenTTLGT applies the GT predicate on the "access_token_ttl" field.
func AccessTokenTTLGT(v int) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldAccessTokenTTL, v))
}

// AccessTokenTTLGTE applies the GTE predicate on the "access_token_ttl" field.
func AccessTokenTTLGTE(v int) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldAccessTokenTTL, v))
}

// AccessTokenTTLLT applies the LT predicate on the "access_token_ttl" field.
func AccessTokenTTLLT(v int) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldAccessTokenTTL, v))
}

// AccessTokenTTLLTE applies the LTE predicate on the "access_token_ttl" field.
func AccessTokenTTLLTE(v int) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldAccessTokenTTL, v))
}

// RefreshTokenTTLEQ applies the EQ predicate on the "refresh_token_ttl" field.
func RefreshTokenTTLEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldRefreshTokenTTL, v))
}

// RefreshTokenTTLNEQ applies the NEQ predicate on the "refresh_token_ttl" field.
func RefreshTokenTTLNEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldRefreshTokenTTL, v))
}

// RefreshTokenTTLIn applies the In predicate on the "refresh_token_ttl" field.
func RefreshTokenTTLIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldRefreshTokenTTL, vs...))
}

// RefreshTokenTTLNotIn applies the NotIn predicate on the "refresh_token_ttl" field.
func RefreshTokenTTLNotIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldRefreshTokenTTL, vs...))
}

// RefreshTokenTTLGT applies the GT predicate on the "refresh_token_ttl" field.
func RefreshTokenTTLGT(v int) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldRefreshTokenTTL, v))
}

// RefreshTokenTTLGTE applies the GTE predicate on the "refresh_token_ttl" field.
func RefreshTokenTTLGTE(v int) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldRefreshTokenTTL, v))
}

// RefreshTokenTTLLT applies the LT predicate on the "refresh_token_ttl" field.
func RefreshTokenTTLLT(v int) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldRefreshTokenTTL, v))
}

// RefreshTokenTTLLTE applies the LTE predicate on the "refresh_token_ttl" field.
func RefreshTokenTTLLTE(v int) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldRefreshTokenTTL, v))
}

// RefreshTokenRotationEQ applies the EQ predicate on the "refresh_token_rotation" field.
func RefreshTokenRotationEQ(v bool) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldRefreshTokenRotation, v))
}

// RefreshTokenRotationNEQ applies the NEQ predicate on the "refresh_token_rotation" field.
func RefreshTokenRotationNEQ(v bool) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldRefreshTokenRotation, v))
}

// FirstPartyEQ applies the EQ predicate on the "first_party" field.
func FirstPartyEQ(v bool) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldFirstParty, v))
}

// FirstPartyNEQ applies the NEQ predicate on the "first_party" field.
func FirstPartyNEQ(v bool) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldFirstParty, v))
}

// PublicEQ applies the EQ predicate on the "public" field.
func PublicEQ(v bool) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldPublic, v))
}

// PublicNEQ applies the NEQ predicate on the "public" field.
func PublicNEQ(v bool) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldPublic, v))
}

// HasPrincipal applies the HasEdge predicate on the "principal" edge.
func HasPrincipal() predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PrincipalTable, PrincipalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrincipalWith applies the HasEdge predicate on the "principal" edge with a given conditions (other predicates).
func HasPrincipalWith(preds ...predicate.Principal) predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := newPrincipalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIssuedTokens applies the HasEdge predicate on the "issued_tokens" edge.
func HasIssuedTokens() predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IssuedTokensTable, IssuedTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIssuedTokensWith applies the HasEdge predicate on the "issued_tokens" edge with a given conditions (other predicates).
func HasIssuedTokensWith(preds ...predicate.PrincipalToken) predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := newIssuedTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Application) predicate.Application {
	return predicate.Application(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Application) predicate.Application {
	return predicate.Application(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Application) predicate.Application {
	return predicate.Application(sql.NotPredicates(p))
}
