// Code generated by ent, DO NOT EDIT.

package oauthconsent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/grokify/systemforge/identity/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldUserID, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldAppID, v))
}

// Granted applies equality check predicate on the "granted" field. It's identical to GrantedEQ.
func Granted(v bool) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldGranted, v))
}

// GrantedAt applies equality check predicate on the "granted_at" field. It's identical to GrantedAtEQ.
func GrantedAt(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldGrantedAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldLastUsedAt, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldRevoked, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedReason applies equality check predicate on the "revoked_reason" field. It's identical to RevokedReasonEQ.
func RevokedReason(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldRevokedReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotIn(FieldUserID, vs...))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...uuid.UUID) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotIn(FieldAppID, vs...))
}

// GrantedEQ applies the EQ predicate on the "granted" field.
func GrantedEQ(v bool) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldGranted, v))
}

// GrantedNEQ applies the NEQ predicate on the "granted" field.
func GrantedNEQ(v bool) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldGranted, v))
}

// GrantedAtEQ applies the EQ predicate on the "granted_at" field.
func GrantedAtEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldGrantedAt, v))
}

// GrantedAtNEQ applies the NEQ predicate on the "granted_at" field.
func GrantedAtNEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldGrantedAt, v))
}

// GrantedAtIn applies the In predicate on the "granted_at" field.
func GrantedAtIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIn(FieldGrantedAt, vs...))
}

// GrantedAtNotIn applies the NotIn predicate on the "granted_at" field.
func GrantedAtNotIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotIn(FieldGrantedAt, vs...))
}

// GrantedAtGT applies the GT predicate on the "granted_at" field.
func GrantedAtGT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGT(FieldGrantedAt, v))
}

// GrantedAtGTE applies the GTE predicate on the "granted_at" field.
func GrantedAtGTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGTE(FieldGrantedAt, v))
}

// GrantedAtLT applies the LT predicate on the "granted_at" field.
func GrantedAtLT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLT(FieldGrantedAt, v))
}

// GrantedAtLTE applies the LTE predicate on the "granted_at" field.
func GrantedAtLTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLTE(FieldGrantedAt, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotNull(FieldLastUsedAt))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldRevoked, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotNull(FieldRevokedAt))
}

// RevokedReasonEQ applies the EQ predicate on the "revoked_reason" field.
func RevokedReasonEQ(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldRevokedReason, v))
}

// RevokedReasonNEQ applies the NEQ predicate on the "revoked_reason" field.
func RevokedReasonNEQ(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldRevokedReason, v))
}

// RevokedReasonIn applies the In predicate on the "revoked_reason" field.
func RevokedReasonIn(vs ...string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIn(FieldRevokedReason, vs...))
}

// RevokedReasonNotIn applies the NotIn predicate on the "revoked_reason" field.
func RevokedReasonNotIn(vs ...string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotIn(FieldRevokedReason, vs...))
}

// RevokedReasonGT applies the GT predicate on the "revoked_reason" field.
func RevokedReasonGT(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGT(FieldRevokedReason, v))
}

// RevokedReasonGTE applies the GTE predicate on the "revoked_reason" field.
func RevokedReasonGTE(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGTE(FieldRevokedReason, v))
}

// RevokedReasonLT applies the LT predicate on the "revoked_reason" field.
func RevokedReasonLT(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLT(FieldRevokedReason, v))
}

// RevokedReasonLTE applies the LTE predicate on the "revoked_reason" field.
func RevokedReasonLTE(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLTE(FieldRevokedReason, v))
}

// RevokedReasonContains applies the Contains predicate on the "revoked_reason" field.
func RevokedReasonContains(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldContains(FieldRevokedReason, v))
}

// RevokedReasonHasPrefix applies the HasPrefix predicate on the "revoked_reason" field.
func RevokedReasonHasPrefix(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldHasPrefix(FieldRevokedReason, v))
}

// RevokedReasonHasSuffix applies the HasSuffix predicate on the "revoked_reason" field.
func RevokedReasonHasSuffix(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldHasSuffix(FieldRevokedReason, v))
}

// RevokedReasonIsNil applies the IsNil predicate on the "revoked_reason" field.
func RevokedReasonIsNil() predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIsNull(FieldRevokedReason))
}

// RevokedReasonNotNil applies the NotNil predicate on the "revoked_reason" field.
func RevokedReasonNotNil() predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotNull(FieldRevokedReason))
}

// RevokedReasonEqualFold applies the EqualFold predicate on the "revoked_reason" field.
func RevokedReasonEqualFold(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEqualFold(FieldRevokedReason, v))
}

// RevokedReasonContainsFold applies the ContainsFold predicate on the "revoked_reason" field.
func RevokedReasonContainsFold(v string) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldContainsFold(FieldRevokedReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OAuthConsent {
	return predicate.OAuthConsent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OAuthConsent {
	return predicate.OAuthConsent(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApp applies the HasEdge predicate on the "app" edge.
func HasApp() predicate.OAuthConsent {
	return predicate.OAuthConsent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AppTable, AppColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAppWith applies the HasEdge predicate on the "app" edge with a given conditions (other predicates).
func HasAppWith(preds ...predicate.OAuthApp) predicate.OAuthConsent {
	return predicate.OAuthConsent(func(s *sql.Selector) {
		step := newAppStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthConsent) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthConsent) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthConsent) predicate.OAuthConsent {
	return predicate.OAuthConsent(sql.NotPredicates(p))
}
