// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/grokify/coreforge/identity/ent/agent"
	"github.com/grokify/coreforge/identity/ent/predicate"
	"github.com/grokify/coreforge/identity/ent/principal"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdate) SetUpdatedAt(v time.Time) *AgentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *AgentUpdate) SetModelID(v string) *AgentUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableModelID(v *string) *AgentUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AgentUpdate) SetVersion(v string) *AgentUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableVersion(v *string) *AgentUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *AgentUpdate) ClearVersion() *AgentUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetDelegatingPrincipalID sets the "delegating_principal_id" field.
func (_u *AgentUpdate) SetDelegatingPrincipalID(v uuid.UUID) *AgentUpdate {
	_u.mutation.SetDelegatingPrincipalID(v)
	return _u
}

// SetNillableDelegatingPrincipalID sets the "delegating_principal_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableDelegatingPrincipalID(v *uuid.UUID) *AgentUpdate {
	if v != nil {
		_u.SetDelegatingPrincipalID(*v)
	}
	return _u
}

// ClearDelegatingPrincipalID clears the value of the "delegating_principal_id" field.
func (_u *AgentUpdate) ClearDelegatingPrincipalID() *AgentUpdate {
	_u.mutation.ClearDelegatingPrincipalID()
	return _u
}

// SetCapabilityConstraints sets the "capability_constraints" field.
func (_u *AgentUpdate) SetCapabilityConstraints(v []string) *AgentUpdate {
	_u.mutation.SetCapabilityConstraints(v)
	return _u
}

// AppendCapabilityConstraints appends value to the "capability_constraints" field.
func (_u *AgentUpdate) AppendCapabilityConstraints(v []string) *AgentUpdate {
	_u.mutation.AppendCapabilityConstraints(v)
	return _u
}

// SetResourceConstraints sets the "resource_constraints" field.
func (_u *AgentUpdate) SetResourceConstraints(v []string) *AgentUpdate {
	_u.mutation.SetResourceConstraints(v)
	return _u
}

// AppendResourceConstraints appends value to the "resource_constraints" field.
func (_u *AgentUpdate) AppendResourceConstraints(v []string) *AgentUpdate {
	_u.mutation.AppendResourceConstraints(v)
	return _u
}

// SetMaxTokenLifetime sets the "max_token_lifetime" field.
func (_u *AgentUpdate) SetMaxTokenLifetime(v int) *AgentUpdate {
	_u.mutation.ResetMaxTokenLifetime()
	_u.mutation.SetMaxTokenLifetime(v)
	return _u
}

// SetNillableMaxTokenLifetime sets the "max_token_lifetime" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableMaxTokenLifetime(v *int) *AgentUpdate {
	if v != nil {
		_u.SetMaxTokenLifetime(*v)
	}
	return _u
}

// AddMaxTokenLifetime adds value to the "max_token_lifetime" field.
func (_u *AgentUpdate) AddMaxTokenLifetime(v int) *AgentUpdate {
	_u.mutation.AddMaxTokenLifetime(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AgentUpdate) SetSessionID(v string) *AgentUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableSessionID(v *string) *AgentUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AgentUpdate) ClearSessionID() *AgentUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetRequiresConfirmation sets the "requires_confirmation" field.
func (_u *AgentUpdate) SetRequiresConfirmation(v bool) *AgentUpdate {
	_u.mutation.SetRequiresConfirmation(v)
	return _u
}

// SetNillableRequiresConfirmation sets the "requires_confirmation" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableRequiresConfirmation(v *bool) *AgentUpdate {
	if v != nil {
		_u.SetRequiresConfirmation(*v)
	}
	return _u
}

// SetDelegatingPrincipal sets the "delegating_principal" edge to the Principal entity.
func (_u *AgentUpdate) SetDelegatingPrincipal(v *Principal) *AgentUpdate {
	return _u.SetDelegatingPrincipalID(v.ID)
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdate) Mutation() *AgentMutation {
	return _u.mutation
}

// ClearDelegatingPrincipal clears the "delegating_principal" edge to the Principal entity.
func (_u *AgentUpdate) ClearDelegatingPrincipal() *AgentUpdate {
	_u.mutation.ClearDelegatingPrincipal()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := agent.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "Agent.model_id": %w`, err)}
		}
	}
	if _u.mutation.PrincipalCleared() && len(_u.mutation.PrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Agent.principal"`)
	}
	return nil
}

func (_u *AgentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(agent.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(agent.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.CapabilityConstraints(); ok {
		_spec.SetField(agent.FieldCapabilityConstraints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilityConstraints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldCapabilityConstraints, value)
		})
	}
	if value, ok := _u.mutation.ResourceConstraints(); ok {
		_spec.SetField(agent.FieldResourceConstraints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResourceConstraints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldResourceConstraints, value)
		})
	}
	if value, ok := _u.mutation.MaxTokenLifetime(); ok {
		_spec.SetField(agent.FieldMaxTokenLifetime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokenLifetime(); ok {
		_spec.AddField(agent.FieldMaxTokenLifetime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(agent.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(agent.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.RequiresConfirmation(); ok {
		_spec.SetField(agent.FieldRequiresConfirmation, field.TypeBool, value)
	}
	if _u.mutation.DelegatingPrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agent.DelegatingPrincipalTable,
			Columns: []string{agent.DelegatingPrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DelegatingPrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agent.DelegatingPrincipalTable,
			Columns: []string{agent.DelegatingPrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdateOne) SetUpdatedAt(v time.Time) *AgentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *AgentUpdateOne) SetModelID(v string) *AgentUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableModelID(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AgentUpdateOne) SetVersion(v string) *AgentUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableVersion(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *AgentUpdateOne) ClearVersion() *AgentUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetDelegatingPrincipalID sets the "delegating_principal_id" field.
func (_u *AgentUpdateOne) SetDelegatingPrincipalID(v uuid.UUID) *AgentUpdateOne {
	_u.mutation.SetDelegatingPrincipalID(v)
	return _u
}

// SetNillableDelegatingPrincipalID sets the "delegating_principal_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableDelegatingPrincipalID(v *uuid.UUID) *AgentUpdateOne {
	if v != nil {
		_u.SetDelegatingPrincipalID(*v)
	}
	return _u
}

// ClearDelegatingPrincipalID clears the value of the "delegating_principal_id" field.
func (_u *AgentUpdateOne) ClearDelegatingPrincipalID() *AgentUpdateOne {
	_u.mutation.ClearDelegatingPrincipalID()
	return _u
}

// SetCapabilityConstraints sets the "capability_constraints" field.
func (_u *AgentUpdateOne) SetCapabilityConstraints(v []string) *AgentUpdateOne {
	_u.mutation.SetCapabilityConstraints(v)
	return _u
}

// AppendCapabilityConstraints appends value to the "capability_constraints" field.
func (_u *AgentUpdateOne) AppendCapabilityConstraints(v []string) *AgentUpdateOne {
	_u.mutation.AppendCapabilityConstraints(v)
	return _u
}

// SetResourceConstraints sets the "resource_constraints" field.
func (_u *AgentUpdateOne) SetResourceConstraints(v []string) *AgentUpdateOne {
	_u.mutation.SetResourceConstraints(v)
	return _u
}

// AppendResourceConstraints appends value to the "resource_constraints" field.
func (_u *AgentUpdateOne) AppendResourceConstraints(v []string) *AgentUpdateOne {
	_u.mutation.AppendResourceConstraints(v)
	return _u
}

// SetMaxTokenLifetime sets the "max_token_lifetime" field.
func (_u *AgentUpdateOne) SetMaxTokenLifetime(v int) *AgentUpdateOne {
	_u.mutation.ResetMaxTokenLifetime()
	_u.mutation.SetMaxTokenLifetime(v)
	return _u
}

// SetNillableMaxTokenLifetime sets the "max_token_lifetime" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableMaxTokenLifetime(v *int) *AgentUpdateOne {
	if v != nil {
		_u.SetMaxTokenLifetime(*v)
	}
	return _u
}

// AddMaxTokenLifetime adds value to the "max_token_lifetime" field.
func (_u *AgentUpdateOne) AddMaxTokenLifetime(v int) *AgentUpdateOne {
	_u.mutation.AddMaxTokenLifetime(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AgentUpdateOne) SetSessionID(v string) *AgentUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableSessionID(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AgentUpdateOne) ClearSessionID() *AgentUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetRequiresConfirmation sets the "requires_confirmation" field.
func (_u *AgentUpdateOne) SetRequiresConfirmation(v bool) *AgentUpdateOne {
	_u.mutation.SetRequiresConfirmation(v)
	return _u
}

// SetNillableRequiresConfirmation sets the "requires_confirmation" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableRequiresConfirmation(v *bool) *AgentUpdateOne {
	if v != nil {
		_u.SetRequiresConfirmation(*v)
	}
	return _u
}

// SetDelegatingPrincipal sets the "delegating_principal" edge to the Principal entity.
func (_u *AgentUpdateOne) SetDelegatingPrincipal(v *Principal) *AgentUpdateOne {
	return _u.SetDelegatingPrincipalID(v.ID)
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdateOne) Mutation() *AgentMutation {
	return _u.mutation
}

// ClearDelegatingPrincipal clears the "delegating_principal" edge to the Principal entity.
func (_u *AgentUpdateOne) ClearDelegatingPrincipal() *AgentUpdateOne {
	_u.mutation.ClearDelegatingPrincipal()
	return _u
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Agent entity.
func (_u *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := agent.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "Agent.model_id": %w`, err)}
		}
	}
	if _u.mutation.PrincipalCleared() && len(_u.mutation.PrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Agent.principal"`)
	}
	return nil
}

func (_u *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(agent.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(agent.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.CapabilityConstraints(); ok {
		_spec.SetField(agent.FieldCapabilityConstraints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilityConstraints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldCapabilityConstraints, value)
		})
	}
	if value, ok := _u.mutation.ResourceConstraints(); ok {
		_spec.SetField(agent.FieldResourceConstraints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResourceConstraints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldResourceConstraints, value)
		})
	}
	if value, ok := _u.mutation.MaxTokenLifetime(); ok {
		_spec.SetField(agent.FieldMaxTokenLifetime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTokenLifetime(); ok {
		_spec.AddField(agent.FieldMaxTokenLifetime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(agent.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(agent.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.RequiresConfirmation(); ok {
		_spec.SetField(agent.FieldRequiresConfirmation, field.TypeBool, value)
	}
	if _u.mutation.DelegatingPrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agent.DelegatingPrincipalTable,
			Columns: []string{agent.DelegatingPrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DelegatingPrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agent.DelegatingPrincipalTable,
			Columns: []string{agent.DelegatingPrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Agent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
