// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/grokify/coreforge/identity/ent/agent"
	"github.com/grokify/coreforge/identity/ent/principal"
)

// AgentCreate is the builder for creating a Agent entity.
type AgentCreate struct {
	config
	mutation *AgentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentCreate) SetCreatedAt(v time.Time) *AgentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableCreatedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentCreate) SetUpdatedAt(v time.Time) *AgentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableUpdatedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPrincipalID sets the "principal_id" field.
func (_c *AgentCreate) SetPrincipalID(v uuid.UUID) *AgentCreate {
	_c.mutation.SetPrincipalID(v)
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *AgentCreate) SetModelID(v string) *AgentCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *AgentCreate) SetVersion(v string) *AgentCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *AgentCreate) SetNillableVersion(v *string) *AgentCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetDelegatingPrincipalID sets the "delegating_principal_id" field.
func (_c *AgentCreate) SetDelegatingPrincipalID(v uuid.UUID) *AgentCreate {
	_c.mutation.SetDelegatingPrincipalID(v)
	return _c
}

// SetNillableDelegatingPrincipalID sets the "delegating_principal_id" field if the given value is not nil.
func (_c *AgentCreate) SetNillableDelegatingPrincipalID(v *uuid.UUID) *AgentCreate {
	if v != nil {
		_c.SetDelegatingPrincipalID(*v)
	}
	return _c
}

// SetCapabilityConstraints sets the "capability_constraints" field.
func (_c *AgentCreate) SetCapabilityConstraints(v []string) *AgentCreate {
	_c.mutation.SetCapabilityConstraints(v)
	return _c
}

// SetResourceConstraints sets the "resource_constraints" field.
func (_c *AgentCreate) SetResourceConstraints(v []string) *AgentCreate {
	_c.mutation.SetResourceConstraints(v)
	return _c
}

// SetMaxTokenLifetime sets the "max_token_lifetime" field.
func (_c *AgentCreate) SetMaxTokenLifetime(v int) *AgentCreate {
	_c.mutation.SetMaxTokenLifetime(v)
	return _c
}

// SetNillableMaxTokenLifetime sets the "max_token_lifetime" field if the given value is not nil.
func (_c *AgentCreate) SetNillableMaxTokenLifetime(v *int) *AgentCreate {
	if v != nil {
		_c.SetMaxTokenLifetime(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AgentCreate) SetSessionID(v string) *AgentCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *AgentCreate) SetNillableSessionID(v *string) *AgentCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetRequiresConfirmation sets the "requires_confirmation" field.
func (_c *AgentCreate) SetRequiresConfirmation(v bool) *AgentCreate {
	_c.mutation.SetRequiresConfirmation(v)
	return _c
}

// SetNillableRequiresConfirmation sets the "requires_confirmation" field if the given value is not nil.
func (_c *AgentCreate) SetNillableRequiresConfirmation(v *bool) *AgentCreate {
	if v != nil {
		_c.SetRequiresConfirmation(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentCreate) SetID(v uuid.UUID) *AgentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentCreate) SetNillableID(v *uuid.UUID) *AgentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPrincipal sets the "principal" edge to the Principal entity.
func (_c *AgentCreate) SetPrincipal(v *Principal) *AgentCreate {
	return _c.SetPrincipalID(v.ID)
}

// SetDelegatingPrincipal sets the "delegating_principal" edge to the Principal entity.
func (_c *AgentCreate) SetDelegatingPrincipal(v *Principal) *AgentCreate {
	return _c.SetDelegatingPrincipalID(v.ID)
}

// Mutation returns the AgentMutation object of the builder.
func (_c *AgentCreate) Mutation() *AgentMutation {
	return _c.mutation
}

// Save creates the Agent in the database.
func (_c *AgentCreate) Save(ctx context.Context) (*Agent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentCreate) SaveX(ctx context.Context) *Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CapabilityConstraints(); !ok {
		v := agent.DefaultCapabilityConstraints
		_c.mutation.SetCapabilityConstraints(v)
	}
	if _, ok := _c.mutation.ResourceConstraints(); !ok {
		v := agent.DefaultResourceConstraints
		_c.mutation.SetResourceConstraints(v)
	}
	if _, ok := _c.mutation.MaxTokenLifetime(); !ok {
		v := agent.DefaultMaxTokenLifetime
		_c.mutation.SetMaxTokenLifetime(v)
	}
	if _, ok := _c.mutation.RequiresConfirmation(); !ok {
		v := agent.DefaultRequiresConfirmation
		_c.mutation.SetRequiresConfirmation(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Agent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Agent.updated_at"`)}
	}
	if _, ok := _c.mutation.PrincipalID(); !ok {
		return &ValidationError{Name: "principal_id", err: errors.New(`ent: missing required field "Agent.principal_id"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "Agent.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := agent.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "Agent.model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CapabilityConstraints(); !ok {
		return &ValidationError{Name: "capability_constraints", err: errors.New(`ent: missing required field "Agent.capability_constraints"`)}
	}
	if _, ok := _c.mutation.ResourceConstraints(); !ok {
		return &ValidationError{Name: "resource_constraints", err: errors.New(`ent: missing required field "Agent.resource_constraints"`)}
	}
	if _, ok := _c.mutation.MaxTokenLifetime(); !ok {
		return &ValidationError{Name: "max_token_lifetime", err: errors.New(`ent: missing required field "Agent.max_token_lifetime"`)}
	}
	if _, ok := _c.mutation.RequiresConfirmation(); !ok {
		return &ValidationError{Name: "requires_confirmation", err: errors.New(`ent: missing required field "Agent.requires_confirmation"`)}
	}
	if len(_c.mutation.PrincipalIDs()) == 0 {
		return &ValidationError{Name: "principal", err: errors.New(`ent: missing required edge "Agent.principal"`)}
	}
	return nil
}

func (_c *AgentCreate) sqlSave(ctx context.Context) (*Agent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentCreate) createSpec() (*Agent, *sqlgraph.CreateSpec) {
	var (
		_node = &Agent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agent.Table, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(agent.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CapabilityConstraints(); ok {
		_spec.SetField(agent.FieldCapabilityConstraints, field.TypeJSON, value)
		_node.CapabilityConstraints = value
	}
	if value, ok := _c.mutation.ResourceConstraints(); ok {
		_spec.SetField(agent.FieldResourceConstraints, field.TypeJSON, value)
		_node.ResourceConstraints = value
	}
	if value, ok := _c.mutation.MaxTokenLifetime(); ok {
		_spec.SetField(agent.FieldMaxTokenLifetime, field.TypeInt, value)
		_node.MaxTokenLifetime = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(agent.FieldSessionID, field.TypeString, value)
		_node.SessionID = &value
	}
	if value, ok := _c.mutation.RequiresConfirmation(); ok {
		_spec.SetField(agent.FieldRequiresConfirmation, field.TypeBool, value)
		_node.RequiresConfirmation = value
	}
	if nodes := _c.mutation.PrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   agent.PrincipalTable,
			Columns: []string{agent.PrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PrincipalID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DelegatingPrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agent.DelegatingPrincipalTable,
			Columns: []string{agent.DelegatingPrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DelegatingPrincipalID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Agent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentCreate) OnConflict(opts ...sql.ConflictOption) *AgentUpsertOne {
	_c.conflict = opts
	return &AgentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentCreate) OnConflictColumns(columns ...string) *AgentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentUpsertOne{
		create: _c,
	}
}

type (
	// AgentUpsertOne is the builder for "upsert"-ing
	//  one Agent node.
	AgentUpsertOne struct {
		create *AgentCreate
	}

	// AgentUpsert is the "OnConflict" setter.
	AgentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentUpsert) SetUpdatedAt(v time.Time) *AgentUpsert {
	u.Set(agent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentUpsert) UpdateUpdatedAt() *AgentUpsert {
	u.SetExcluded(agent.FieldUpdatedAt)
	return u
}

// SetModelID sets the "model_id" field.
func (u *AgentUpsert) SetModelID(v string) *AgentUpsert {
	u.Set(agent.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *AgentUpsert) UpdateModelID() *AgentUpsert {
	u.SetExcluded(agent.FieldModelID)
	return u
}

// SetVersion sets the "version" field.
func (u *AgentUpsert) SetVersion(v string) *AgentUpsert {
	u.Set(agent.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *AgentUpsert) UpdateVersion() *AgentUpsert {
	u.SetExcluded(agent.FieldVersion)
	return u
}

// ClearVersion clears the value of the "version" field.
func (u *AgentUpsert) ClearVersion() *AgentUpsert {
	u.SetNull(agent.FieldVersion)
	return u
}

// SetDelegatingPrincipalID sets the "delegating_principal_id" field.
func (u *AgentUpsert) SetDelegatingPrincipalID(v uuid.UUID) *AgentUpsert {
	u.Set(agent.FieldDelegatingPrincipalID, v)
	return u
}

// UpdateDelegatingPrincipalID sets the "delegating_principal_id" field to the value that was provided on create.
func (u *AgentUpsert) UpdateDelegatingPrincipalID() *AgentUpsert {
	u.SetExcluded(agent.FieldDelegatingPrincipalID)
	return u
}

// ClearDelegatingPrincipalID clears the value of the "delegating_principal_id" field.
func (u *AgentUpsert) ClearDelegatingPrincipalID() *AgentUpsert {
	u.SetNull(agent.FieldDelegatingPrincipalID)
	return u
}

// SetCapabilityConstraints sets the "capability_constraints" field.
func (u *AgentUpsert) SetCapabilityConstraints(v []string) *AgentUpsert {
	u.Set(agent.FieldCapabilityConstraints, v)
	return u
}

// UpdateCapabilityConstraints sets the "capability_constraints" field to the value that was provided on create.
func (u *AgentUpsert) UpdateCapabilityConstraints() *AgentUpsert {
	u.SetExcluded(agent.FieldCapabilityConstraints)
	return u
}

// SetResourceConstraints sets the "resource_constraints" field.
func (u *AgentUpsert) SetResourceConstraints(v []string) *AgentUpsert {
	u.Set(agent.FieldResourceConstraints, v)
	return u
}

// UpdateResourceConstraints sets the "resource_constraints" field to the value that was provided on create.
func (u *AgentUpsert) UpdateResourceConstraints() *AgentUpsert {
	u.SetExcluded(agent.FieldResourceConstraints)
	return u
}

// SetMaxTokenLifetime sets the "max_token_lifetime" field.
func (u *AgentUpsert) SetMaxTokenLifetime(v int) *AgentUpsert {
	u.Set(agent.FieldMaxTokenLifetime, v)
	return u
}

// UpdateMaxTokenLifetime sets the "max_token_lifetime" field to the value that was provided on create.
func (u *AgentUpsert) UpdateMaxTokenLifetime() *AgentUpsert {
	u.SetExcluded(agent.FieldMaxTokenLifetime)
	return u
}

// AddMaxTokenLifetime adds v to the "max_token_lifetime" field.
func (u *AgentUpsert) AddMaxTokenLifetime(v int) *AgentUpsert {
	u.Add(agent.FieldMaxTokenLifetime, v)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *AgentUpsert) SetSessionID(v string) *AgentUpsert {
	u.Set(agent.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AgentUpsert) UpdateSessionID() *AgentUpsert {
	u.SetExcluded(agent.FieldSessionID)
	return u
}

// ClearSessionID clears the value of the "session_id" field.
func (u *AgentUpsert) ClearSessionID() *AgentUpsert {
	u.SetNull(agent.FieldSessionID)
	return u
}

// SetRequiresConfirmation sets the "requires_confirmation" field.
func (u *AgentUpsert) SetRequiresConfirmation(v bool) *AgentUpsert {
	u.Set(agent.FieldRequiresConfirmation, v)
	return u
}

// UpdateRequiresConfirmation sets the "requires_confirmation" field to the value that was provided on create.
func (u *AgentUpsert) UpdateRequiresConfirmation() *AgentUpsert {
	u.SetExcluded(agent.FieldRequiresConfirmation)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(agent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AgentUpsertOne) UpdateNewValues() *AgentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(agent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(agent.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.PrincipalID(); exists {
			s.SetIgnore(agent.FieldPrincipalID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Agent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AgentUpsertOne) Ignore() *AgentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentUpsertOne) DoNothing() *AgentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentCreate.OnConflict
// documentation for more info.
func (u *AgentUpsertOne) Update(set func(*AgentUpsert)) *AgentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentUpsertOne) SetUpdatedAt(v time.Time) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateUpdatedAt() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetModelID sets the "model_id" field.
func (u *AgentUpsertOne) SetModelID(v string) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateModelID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateModelID()
	})
}

// SetVersion sets the "version" field.
func (u *AgentUpsertOne) SetVersion(v string) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateVersion() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateVersion()
	})
}

// ClearVersion clears the value of the "version" field.
func (u *AgentUpsertOne) ClearVersion() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.ClearVersion()
	})
}

// SetDelegatingPrincipalID sets the "delegating_principal_id" field.
func (u *AgentUpsertOne) SetDelegatingPrincipalID(v uuid.UUID) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetDelegatingPrincipalID(v)
	})
}

// UpdateDelegatingPrincipalID sets the "delegating_principal_id" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateDelegatingPrincipalID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateDelegatingPrincipalID()
	})
}

// ClearDelegatingPrincipalID clears the value of the "delegating_principal_id" field.
func (u *AgentUpsertOne) ClearDelegatingPrincipalID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.ClearDelegatingPrincipalID()
	})
}

// SetCapabilityConstraints sets the "capability_constraints" field.
func (u *AgentUpsertOne) SetCapabilityConstraints(v []string) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetCapabilityConstraints(v)
	})
}

// UpdateCapabilityConstraints sets the "capability_constraints" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateCapabilityConstraints() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateCapabilityConstraints()
	})
}

// SetResourceConstraints sets the "resource_constraints" field.
func (u *AgentUpsertOne) SetResourceConstraints(v []string) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetResourceConstraints(v)
	})
}

// UpdateResourceConstraints sets the "resource_constraints" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateResourceConstraints() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateResourceConstraints()
	})
}

// SetMaxTokenLifetime sets the "max_token_lifetime" field.
func (u *AgentUpsertOne) SetMaxTokenLifetime(v int) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetMaxTokenLifetime(v)
	})
}

// AddMaxTokenLifetime adds v to the "max_token_lifetime" field.
func (u *AgentUpsertOne) AddMaxTokenLifetime(v int) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.AddMaxTokenLifetime(v)
	})
}

// UpdateMaxTokenLifetime sets the "max_token_lifetime" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateMaxTokenLifetime() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateMaxTokenLifetime()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AgentUpsertOne) SetSessionID(v string) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateSessionID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *AgentUpsertOne) ClearSessionID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.ClearSessionID()
	})
}

// SetRequiresConfirmation sets the "requires_confirmation" field.
func (u *AgentUpsertOne) SetRequiresConfirmation(v bool) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetRequiresConfirmation(v)
	})
}

// UpdateRequiresConfirmation sets the "requires_confirmation" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateRequiresConfirmation() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateRequiresConfirmation()
	})
}

// Exec executes the query.
func (u *AgentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AgentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AgentUpsertOne.ID is not supported by MySQL driver. Use AgentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AgentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AgentCreateBulk is the builder for creating many Agent entities in bulk.
type AgentCreateBulk struct {
	config
	err      error
	builders []*AgentCreate
	conflict []sql.ConflictOption
}

// Save creates the Agent entities in the database.
func (_c *AgentCreateBulk) Save(ctx context.Context) ([]*Agent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Agent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentCreateBulk) SaveX(ctx context.Context) []*Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Agent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentCreateBulk) OnConflict(opts ...sql.ConflictOption) *AgentUpsertBulk {
	_c.conflict = opts
	return &AgentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentCreateBulk) OnConflictColumns(columns ...string) *AgentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentUpsertBulk{
		create: _c,
	}
}

// AgentUpsertBulk is the builder for "upsert"-ing
// a bulk of Agent nodes.
type AgentUpsertBulk struct {
	create *AgentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(agent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AgentUpsertBulk) UpdateNewValues() *AgentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(agent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(agent.FieldCreatedAt)
			}
			if _, exists := b.mutation.PrincipalID(); exists {
				s.SetIgnore(agent.FieldPrincipalID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AgentUpsertBulk) Ignore() *AgentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentUpsertBulk) DoNothing() *AgentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentCreateBulk.OnConflict
// documentation for more info.
func (u *AgentUpsertBulk) Update(set func(*AgentUpsert)) *AgentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentUpsertBulk) SetUpdatedAt(v time.Time) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateUpdatedAt() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetModelID sets the "model_id" field.
func (u *AgentUpsertBulk) SetModelID(v string) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateModelID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateModelID()
	})
}

// SetVersion sets the "version" field.
func (u *AgentUpsertBulk) SetVersion(v string) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateVersion() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateVersion()
	})
}

// ClearVersion clears the value of the "version" field.
func (u *AgentUpsertBulk) ClearVersion() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.ClearVersion()
	})
}

// SetDelegatingPrincipalID sets the "delegating_principal_id" field.
func (u *AgentUpsertBulk) SetDelegatingPrincipalID(v uuid.UUID) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetDelegatingPrincipalID(v)
	})
}

// UpdateDelegatingPrincipalID sets the "delegating_principal_id" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateDelegatingPrincipalID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateDelegatingPrincipalID()
	})
}

// ClearDelegatingPrincipalID clears the value of the "delegating_principal_id" field.
func (u *AgentUpsertBulk) ClearDelegatingPrincipalID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.ClearDelegatingPrincipalID()
	})
}

// SetCapabilityConstraints sets the "capability_constraints" field.
func (u *AgentUpsertBulk) SetCapabilityConstraints(v []string) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetCapabilityConstraints(v)
	})
}

// UpdateCapabilityConstraints sets the "capability_constraints" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateCapabilityConstraints() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateCapabilityConstraints()
	})
}

// SetResourceConstraints sets the "resource_constraints" field.
func (u *AgentUpsertBulk) SetResourceConstraints(v []string) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetResourceConstraints(v)
	})
}

// UpdateResourceConstraints sets the "resource_constraints" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateResourceConstraints() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateResourceConstraints()
	})
}

// SetMaxTokenLifetime sets the "max_token_lifetime" field.
func (u *AgentUpsertBulk) SetMaxTokenLifetime(v int) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetMaxTokenLifetime(v)
	})
}

// AddMaxTokenLifetime adds v to the "max_token_lifetime" field.
func (u *AgentUpsertBulk) AddMaxTokenLifetime(v int) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.AddMaxTokenLifetime(v)
	})
}

// UpdateMaxTokenLifetime sets the "max_token_lifetime" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateMaxTokenLifetime() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateMaxTokenLifetime()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AgentUpsertBulk) SetSessionID(v string) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateSessionID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *AgentUpsertBulk) ClearSessionID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.ClearSessionID()
	})
}

// SetRequiresConfirmation sets the "requires_confirmation" field.
func (u *AgentUpsertBulk) SetRequiresConfirmation(v bool) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetRequiresConfirmation(v)
	})
}

// UpdateRequiresConfirmation sets the "requires_confirmation" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateRequiresConfirmation() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateRequiresConfirmation()
	})
}

// Exec executes the query.
func (u *AgentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AgentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
