// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/grokify/systemforge/identity/ent/application"
	"github.com/grokify/systemforge/identity/ent/principal"
	"github.com/grokify/systemforge/identity/ent/principaltoken"
)

// ApplicationCreate is the builder for creating a Application entity.
type ApplicationCreate struct {
	config
	mutation *ApplicationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApplicationCreate) SetCreatedAt(v time.Time) *ApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableCreatedAt(v *time.Time) *ApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ApplicationCreate) SetUpdatedAt(v time.Time) *ApplicationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableUpdatedAt(v *time.Time) *ApplicationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPrincipalID sets the "principal_id" field.
func (_c *ApplicationCreate) SetPrincipalID(v uuid.UUID) *ApplicationCreate {
	_c.mutation.SetPrincipalID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *ApplicationCreate) SetClientID(v string) *ApplicationCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ApplicationCreate) SetDescription(v string) *ApplicationCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableDescription(v *string) *ApplicationCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLogoURL sets the "logo_url" field.
func (_c *ApplicationCreate) SetLogoURL(v string) *ApplicationCreate {
	_c.mutation.SetLogoURL(v)
	return _c
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableLogoURL(v *string) *ApplicationCreate {
	if v != nil {
		_c.SetLogoURL(*v)
	}
	return _c
}

// SetAppType sets the "app_type" field.
func (_c *ApplicationCreate) SetAppType(v application.AppType) *ApplicationCreate {
	_c.mutation.SetAppType(v)
	return _c
}

// SetNillableAppType sets the "app_type" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableAppType(v *application.AppType) *ApplicationCreate {
	if v != nil {
		_c.SetAppType(*v)
	}
	return _c
}

// SetRedirectUris sets the "redirect_uris" field.
func (_c *ApplicationCreate) SetRedirectUris(v []string) *ApplicationCreate {
	_c.mutation.SetRedirectUris(v)
	return _c
}

// SetAllowedGrants sets the "allowed_grants" field.
func (_c *ApplicationCreate) SetAllowedGrants(v []string) *ApplicationCreate {
	_c.mutation.SetAllowedGrants(v)
	return _c
}

// SetAllowedResponseTypes sets the "allowed_response_types" field.
func (_c *ApplicationCreate) SetAllowedResponseTypes(v []string) *ApplicationCreate {
	_c.mutation.SetAllowedResponseTypes(v)
	return _c
}

// SetAccessTokenTTL sets the "access_token_ttl" field.
func (_c *ApplicationCreate) SetAccessTokenTTL(v int) *ApplicationCreate {
	_c.mutation.SetAccessTokenTTL(v)
	return _c
}

// SetNillableAccessTokenTTL sets the "access_token_ttl" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableAccessTokenTTL(v *int) *ApplicationCreate {
	if v != nil {
		_c.SetAccessTokenTTL(*v)
	}
	return _c
}

// SetRefreshTokenTTL sets the "refresh_token_ttl" field.
func (_c *ApplicationCreate) SetRefreshTokenTTL(v int) *ApplicationCreate {
	_c.mutation.SetRefreshTokenTTL(v)
	return _c
}

// SetNillableRefreshTokenTTL sets the "refresh_token_ttl" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableRefreshTokenTTL(v *int) *ApplicationCreate {
	if v != nil {
		_c.SetRefreshTokenTTL(*v)
	}
	return _c
}

// SetRefreshTokenRotation sets the "refresh_token_rotation" field.
func (_c *ApplicationCreate) SetRefreshTokenRotation(v bool) *ApplicationCreate {
	_c.mutation.SetRefreshTokenRotation(v)
	return _c
}

// SetNillableRefreshTokenRotation sets the "refresh_token_rotation" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableRefreshTokenRotation(v *bool) *ApplicationCreate {
	if v != nil {
		_c.SetRefreshTokenRotation(*v)
	}
	return _c
}

// SetFirstParty sets the "first_party" field.
func (_c *ApplicationCreate) SetFirstParty(v bool) *ApplicationCreate {
	_c.mutation.SetFirstParty(v)
	return _c
}

// SetNillableFirstParty sets the "first_party" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableFirstParty(v *bool) *ApplicationCreate {
	if v != nil {
		_c.SetFirstParty(*v)
	}
	return _c
}

// SetPublic sets the "public" field.
func (_c *ApplicationCreate) SetPublic(v bool) *ApplicationCreate {
	_c.mutation.SetPublic(v)
	return _c
}

// SetNillablePublic sets the "public" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillablePublic(v *bool) *ApplicationCreate {
	if v != nil {
		_c.SetPublic(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ApplicationCreate) SetID(v uuid.UUID) *ApplicationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableID(v *uuid.UUID) *ApplicationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPrincipal sets the "principal" edge to the Principal entity.
func (_c *ApplicationCreate) SetPrincipal(v *Principal) *ApplicationCreate {
	return _c.SetPrincipalID(v.ID)
}

// AddIssuedTokenIDs adds the "issued_tokens" edge to the PrincipalToken entity by IDs.
func (_c *ApplicationCreate) AddIssuedTokenIDs(ids ...uuid.UUID) *ApplicationCreate {
	_c.mutation.AddIssuedTokenIDs(ids...)
	return _c
}

// AddIssuedTokens adds the "issued_tokens" edges to the PrincipalToken entity.
func (_c *ApplicationCreate) AddIssuedTokens(v ...*PrincipalToken) *ApplicationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIssuedTokenIDs(ids...)
}

// Mutation returns the ApplicationMutation object of the builder.
func (_c *ApplicationCreate) Mutation() *ApplicationMutation {
	return _c.mutation
}

// Save creates the Application in the database.
func (_c *ApplicationCreate) Save(ctx context.Context) (*Application, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApplicationCreate) SaveX(ctx context.Context) *Application {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApplicationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := application.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := application.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AppType(); !ok {
		v := application.DefaultAppType
		_c.mutation.SetAppType(v)
	}
	if _, ok := _c.mutation.RedirectUris(); !ok {
		v := application.DefaultRedirectUris
		_c.mutation.SetRedirectUris(v)
	}
	if _, ok := _c.mutation.AllowedGrants(); !ok {
		v := application.DefaultAllowedGrants
		_c.mutation.SetAllowedGrants(v)
	}
	if _, ok := _c.mutation.AllowedResponseTypes(); !ok {
		v := application.DefaultAllowedResponseTypes
		_c.mutation.SetAllowedResponseTypes(v)
	}
	if _, ok := _c.mutation.AccessTokenTTL(); !ok {
		v := application.DefaultAccessTokenTTL
		_c.mutation.SetAccessTokenTTL(v)
	}
	if _, ok := _c.mutation.RefreshTokenTTL(); !ok {
		v := application.DefaultRefreshTokenTTL
		_c.mutation.SetRefreshTokenTTL(v)
	}
	if _, ok := _c.mutation.RefreshTokenRotation(); !ok {
		v := application.DefaultRefreshTokenRotation
		_c.mutation.SetRefreshTokenRotation(v)
	}
	if _, ok := _c.mutation.FirstParty(); !ok {
		v := application.DefaultFirstParty
		_c.mutation.SetFirstParty(v)
	}
	if _, ok := _c.mutation.Public(); !ok {
		v := application.DefaultPublic
		_c.mutation.SetPublic(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := application.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApplicationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Application.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Application.updated_at"`)}
	}
	if _, ok := _c.mutation.PrincipalID(); !ok {
		return &ValidationError{Name: "principal_id", err: errors.New(`ent: missing required field "Application.principal_id"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "Application.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := application.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Application.client_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := application.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Application.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppType(); !ok {
		return &ValidationError{Name: "app_type", err: errors.New(`ent: missing required field "Application.app_type"`)}
	}
	if v, ok := _c.mutation.AppType(); ok {
		if err := application.AppTypeValidator(v); err != nil {
			return &ValidationError{Name: "app_type", err: fmt.Errorf(`ent: validator failed for field "Application.app_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectUris(); !ok {
		return &ValidationError{Name: "redirect_uris", err: errors.New(`ent: missing required field "Application.redirect_uris"`)}
	}
	if _, ok := _c.mutation.AllowedGrants(); !ok {
		return &ValidationError{Name: "allowed_grants", err: errors.New(`ent: missing required field "Application.allowed_grants"`)}
	}
	if _, ok := _c.mutation.AllowedResponseTypes(); !ok {
		return &ValidationError{Name: "allowed_response_types", err: errors.New(`ent: missing required field "Application.allowed_response_types"`)}
	}
	if _, ok := _c.mutation.AccessTokenTTL(); !ok {
		return &ValidationError{Name: "access_token_ttl", err: errors.New(`ent: missing required field "Application.access_token_ttl"`)}
	}
	if _, ok := _c.mutation.RefreshTokenTTL(); !ok {
		return &ValidationError{Name: "refresh_token_ttl", err: errors.New(`ent: missing required field "Application.refresh_token_ttl"`)}
	}
	if _, ok := _c.mutation.RefreshTokenRotation(); !ok {
		return &ValidationError{Name: "refresh_token_rotation", err: errors.New(`ent: missing required field "Application.refresh_token_rotation"`)}
	}
	if _, ok := _c.mutation.FirstParty(); !ok {
		return &ValidationError{Name: "first_party", err: errors.New(`ent: missing required field "Application.first_party"`)}
	}
	if _, ok := _c.mutation.Public(); !ok {
		return &ValidationError{Name: "public", err: errors.New(`ent: missing required field "Application.public"`)}
	}
	if len(_c.mutation.PrincipalIDs()) == 0 {
		return &ValidationError{Name: "principal", err: errors.New(`ent: missing required edge "Application.principal"`)}
	}
	return nil
}

func (_c *ApplicationCreate) sqlSave(ctx context.Context) (*Application, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApplicationCreate) createSpec() (*Application, *sqlgraph.CreateSpec) {
	var (
		_node = &Application{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(application.Table, sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(application.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(application.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(application.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(application.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.LogoURL(); ok {
		_spec.SetField(application.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = value
	}
	if value, ok := _c.mutation.AppType(); ok {
		_spec.SetField(application.FieldAppType, field.TypeEnum, value)
		_node.AppType = value
	}
	if value, ok := _c.mutation.RedirectUris(); ok {
		_spec.SetField(application.FieldRedirectUris, field.TypeJSON, value)
		_node.RedirectUris = value
	}
	if value, ok := _c.mutation.AllowedGrants(); ok {
		_spec.SetField(application.FieldAllowedGrants, field.TypeJSON, value)
		_node.AllowedGrants = value
	}
	if value, ok := _c.mutation.AllowedResponseTypes(); ok {
		_spec.SetField(application.FieldAllowedResponseTypes, field.TypeJSON, value)
		_node.AllowedResponseTypes = value
	}
	if value, ok := _c.mutation.AccessTokenTTL(); ok {
		_spec.SetField(application.FieldAccessTokenTTL, field.TypeInt, value)
		_node.AccessTokenTTL = value
	}
	if value, ok := _c.mutation.RefreshTokenTTL(); ok {
		_spec.SetField(application.FieldRefreshTokenTTL, field.TypeInt, value)
		_node.RefreshTokenTTL = value
	}
	if value, ok := _c.mutation.RefreshTokenRotation(); ok {
		_spec.SetField(application.FieldRefreshTokenRotation, field.TypeBool, value)
		_node.RefreshTokenRotation = value
	}
	if value, ok := _c.mutation.FirstParty(); ok {
		_spec.SetField(application.FieldFirstParty, field.TypeBool, value)
		_node.FirstParty = value
	}
	if value, ok := _c.mutation.Public(); ok {
		_spec.SetField(application.FieldPublic, field.TypeBool, value)
		_node.Public = value
	}
	if nodes := _c.mutation.PrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   application.PrincipalTable,
			Columns: []string{application.PrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PrincipalID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IssuedTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   application.IssuedTokensTable,
			Columns: []string{application.IssuedTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principaltoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Application.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ApplicationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ApplicationCreate) OnConflict(opts ...sql.ConflictOption) *ApplicationUpsertOne {
	_c.conflict = opts
	return &ApplicationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Application.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ApplicationCreate) OnConflictColumns(columns ...string) *ApplicationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ApplicationUpsertOne{
		create: _c,
	}
}

type (
	// ApplicationUpsertOne is the builder for "upsert"-ing
	//  one Application node.
	ApplicationUpsertOne struct {
		create *ApplicationCreate
	}

	// ApplicationUpsert is the "OnConflict" setter.
	ApplicationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ApplicationUpsert) SetUpdatedAt(v time.Time) *ApplicationUpsert {
	u.Set(application.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateUpdatedAt() *ApplicationUpsert {
	u.SetExcluded(application.FieldUpdatedAt)
	return u
}

// SetDescription sets the "description" field.
func (u *ApplicationUpsert) SetDescription(v string) *ApplicationUpsert {
	u.Set(application.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateDescription() *ApplicationUpsert {
	u.SetExcluded(application.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ApplicationUpsert) ClearDescription() *ApplicationUpsert {
	u.SetNull(application.FieldDescription)
	return u
}

// SetLogoURL sets the "logo_url" field.
func (u *ApplicationUpsert) SetLogoURL(v string) *ApplicationUpsert {
	u.Set(application.FieldLogoURL, v)
	return u
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateLogoURL() *ApplicationUpsert {
	u.SetExcluded(application.FieldLogoURL)
	return u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (u *ApplicationUpsert) ClearLogoURL() *ApplicationUpsert {
	u.SetNull(application.FieldLogoURL)
	return u
}

// SetAppType sets the "app_type" field.
func (u *ApplicationUpsert) SetAppType(v application.AppType) *ApplicationUpsert {
	u.Set(application.FieldAppType, v)
	return u
}

// UpdateAppType sets the "app_type" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateAppType() *ApplicationUpsert {
	u.SetExcluded(application.FieldAppType)
	return u
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *ApplicationUpsert) SetRedirectUris(v []string) *ApplicationUpsert {
	u.Set(application.FieldRedirectUris, v)
	return u
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateRedirectUris() *ApplicationUpsert {
	u.SetExcluded(application.FieldRedirectUris)
	return u
}

// SetAllowedGrants sets the "allowed_grants" field.
func (u *ApplicationUpsert) SetAllowedGrants(v []string) *ApplicationUpsert {
	u.Set(application.FieldAllowedGrants, v)
	return u
}

// UpdateAllowedGrants sets the "allowed_grants" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateAllowedGrants() *ApplicationUpsert {
	u.SetExcluded(application.FieldAllowedGrants)
	return u
}

// SetAllowedResponseTypes sets the "allowed_response_types" field.
func (u *ApplicationUpsert) SetAllowedResponseTypes(v []string) *ApplicationUpsert {
	u.Set(application.FieldAllowedResponseTypes, v)
	return u
}

// UpdateAllowedResponseTypes sets the "allowed_response_types" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateAllowedResponseTypes() *ApplicationUpsert {
	u.SetExcluded(application.FieldAllowedResponseTypes)
	return u
}

// SetAccessTokenTTL sets the "access_token_ttl" field.
func (u *ApplicationUpsert) SetAccessTokenTTL(v int) *ApplicationUpsert {
	u.Set(application.FieldAccessTokenTTL, v)
	return u
}

// UpdateAccessTokenTTL sets the "access_token_ttl" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateAccessTokenTTL() *ApplicationUpsert {
	u.SetExcluded(application.FieldAccessTokenTTL)
	return u
}

// AddAccessTokenTTL adds v to the "access_token_ttl" field.
func (u *ApplicationUpsert) AddAccessTokenTTL(v int) *ApplicationUpsert {
	u.Add(application.FieldAccessTokenTTL, v)
	return u
}

// SetRefreshTokenTTL sets the "refresh_token_ttl" field.
func (u *ApplicationUpsert) SetRefreshTokenTTL(v int) *ApplicationUpsert {
	u.Set(application.FieldRefreshTokenTTL, v)
	return u
}

// UpdateRefreshTokenTTL sets the "refresh_token_ttl" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateRefreshTokenTTL() *ApplicationUpsert {
	u.SetExcluded(application.FieldRefreshTokenTTL)
	return u
}

// AddRefreshTokenTTL adds v to the "refresh_token_ttl" field.
func (u *ApplicationUpsert) AddRefreshTokenTTL(v int) *ApplicationUpsert {
	u.Add(application.FieldRefreshTokenTTL, v)
	return u
}

// SetRefreshTokenRotation sets the "refresh_token_rotation" field.
func (u *ApplicationUpsert) SetRefreshTokenRotation(v bool) *ApplicationUpsert {
	u.Set(application.FieldRefreshTokenRotation, v)
	return u
}

// UpdateRefreshTokenRotation sets the "refresh_token_rotation" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateRefreshTokenRotation() *ApplicationUpsert {
	u.SetExcluded(application.FieldRefreshTokenRotation)
	return u
}

// SetFirstParty sets the "first_party" field.
func (u *ApplicationUpsert) SetFirstParty(v bool) *ApplicationUpsert {
	u.Set(application.FieldFirstParty, v)
	return u
}

// UpdateFirstParty sets the "first_party" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdateFirstParty() *ApplicationUpsert {
	u.SetExcluded(application.FieldFirstParty)
	return u
}

// SetPublic sets the "public" field.
func (u *ApplicationUpsert) SetPublic(v bool) *ApplicationUpsert {
	u.Set(application.FieldPublic, v)
	return u
}

// UpdatePublic sets the "public" field to the value that was provided on create.
func (u *ApplicationUpsert) UpdatePublic() *ApplicationUpsert {
	u.SetExcluded(application.FieldPublic)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Application.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(application.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ApplicationUpsertOne) UpdateNewValues() *ApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(application.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(application.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.PrincipalID(); exists {
			s.SetIgnore(application.FieldPrincipalID)
		}
		if _, exists := u.create.mutation.ClientID(); exists {
			s.SetIgnore(application.FieldClientID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Application.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ApplicationUpsertOne) Ignore() *ApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ApplicationUpsertOne) DoNothing() *ApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ApplicationCreate.OnConflict
// documentation for more info.
func (u *ApplicationUpsertOne) Update(set func(*ApplicationUpsert)) *ApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ApplicationUpsertOne) SetUpdatedAt(v time.Time) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateUpdatedAt() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDescription sets the "description" field.
func (u *ApplicationUpsertOne) SetDescription(v string) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateDescription() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ApplicationUpsertOne) ClearDescription() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.ClearDescription()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *ApplicationUpsertOne) SetLogoURL(v string) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateLogoURL() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateLogoURL()
	})
}

// ClearLogoURL clears the value of the "logo_url" field.
func (u *ApplicationUpsertOne) ClearLogoURL() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.ClearLogoURL()
	})
}

// SetAppType sets the "app_type" field.
func (u *ApplicationUpsertOne) SetAppType(v application.AppType) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetAppType(v)
	})
}

// UpdateAppType sets the "app_type" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateAppType() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateAppType()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *ApplicationUpsertOne) SetRedirectUris(v []string) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateRedirectUris() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateRedirectUris()
	})
}

// SetAllowedGrants sets the "allowed_grants" field.
func (u *ApplicationUpsertOne) SetAllowedGrants(v []string) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetAllowedGrants(v)
	})
}

// UpdateAllowedGrants sets the "allowed_grants" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateAllowedGrants() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateAllowedGrants()
	})
}

// SetAllowedResponseTypes sets the "allowed_response_types" field.
func (u *ApplicationUpsertOne) SetAllowedResponseTypes(v []string) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetAllowedResponseTypes(v)
	})
}

// UpdateAllowedResponseTypes sets the "allowed_response_types" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateAllowedResponseTypes() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateAllowedResponseTypes()
	})
}

// SetAccessTokenTTL sets the "access_token_ttl" field.
func (u *ApplicationUpsertOne) SetAccessTokenTTL(v int) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetAccessTokenTTL(v)
	})
}

// AddAccessTokenTTL adds v to the "access_token_ttl" field.
func (u *ApplicationUpsertOne) AddAccessTokenTTL(v int) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.AddAccessTokenTTL(v)
	})
}

// UpdateAccessTokenTTL sets the "access_token_ttl" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateAccessTokenTTL() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateAccessTokenTTL()
	})
}

// SetRefreshTokenTTL sets the "refresh_token_ttl" field.
func (u *ApplicationUpsertOne) SetRefreshTokenTTL(v int) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetRefreshTokenTTL(v)
	})
}

// AddRefreshTokenTTL adds v to the "refresh_token_ttl" field.
func (u *ApplicationUpsertOne) AddRefreshTokenTTL(v int) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.AddRefreshTokenTTL(v)
	})
}

// UpdateRefreshTokenTTL sets the "refresh_token_ttl" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateRefreshTokenTTL() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateRefreshTokenTTL()
	})
}

// SetRefreshTokenRotation sets the "refresh_token_rotation" field.
func (u *ApplicationUpsertOne) SetRefreshTokenRotation(v bool) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetRefreshTokenRotation(v)
	})
}

// UpdateRefreshTokenRotation sets the "refresh_token_rotation" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateRefreshTokenRotation() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateRefreshTokenRotation()
	})
}

// SetFirstParty sets the "first_party" field.
func (u *ApplicationUpsertOne) SetFirstParty(v bool) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetFirstParty(v)
	})
}

// UpdateFirstParty sets the "first_party" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdateFirstParty() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateFirstParty()
	})
}

// SetPublic sets the "public" field.
func (u *ApplicationUpsertOne) SetPublic(v bool) *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetPublic(v)
	})
}

// UpdatePublic sets the "public" field to the value that was provided on create.
func (u *ApplicationUpsertOne) UpdatePublic() *ApplicationUpsertOne {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdatePublic()
	})
}

// Exec executes the query.
func (u *ApplicationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ApplicationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ApplicationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ApplicationUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ApplicationUpsertOne.ID is not supported by MySQL driver. Use ApplicationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ApplicationUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ApplicationCreateBulk is the builder for creating many Application entities in bulk.
type ApplicationCreateBulk struct {
	config
	err      error
	builders []*ApplicationCreate
	conflict []sql.ConflictOption
}

// Save creates the Application entities in the database.
func (_c *ApplicationCreateBulk) Save(ctx context.Context) ([]*Application, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Application, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApplicationCreateBulk) SaveX(ctx context.Context) []*Application {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Application.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ApplicationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ApplicationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ApplicationUpsertBulk {
	_c.conflict = opts
	return &ApplicationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Application.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ApplicationCreateBulk) OnConflictColumns(columns ...string) *ApplicationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ApplicationUpsertBulk{
		create: _c,
	}
}

// ApplicationUpsertBulk is the builder for "upsert"-ing
// a bulk of Application nodes.
type ApplicationUpsertBulk struct {
	create *ApplicationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Application.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(application.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ApplicationUpsertBulk) UpdateNewValues() *ApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(application.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(application.FieldCreatedAt)
			}
			if _, exists := b.mutation.PrincipalID(); exists {
				s.SetIgnore(application.FieldPrincipalID)
			}
			if _, exists := b.mutation.ClientID(); exists {
				s.SetIgnore(application.FieldClientID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Application.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ApplicationUpsertBulk) Ignore() *ApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ApplicationUpsertBulk) DoNothing() *ApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ApplicationCreateBulk.OnConflict
// documentation for more info.
func (u *ApplicationUpsertBulk) Update(set func(*ApplicationUpsert)) *ApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ApplicationUpsertBulk) SetUpdatedAt(v time.Time) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateUpdatedAt() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDescription sets the "description" field.
func (u *ApplicationUpsertBulk) SetDescription(v string) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateDescription() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ApplicationUpsertBulk) ClearDescription() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.ClearDescription()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *ApplicationUpsertBulk) SetLogoURL(v string) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateLogoURL() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateLogoURL()
	})
}

// ClearLogoURL clears the value of the "logo_url" field.
func (u *ApplicationUpsertBulk) ClearLogoURL() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.ClearLogoURL()
	})
}

// SetAppType sets the "app_type" field.
func (u *ApplicationUpsertBulk) SetAppType(v application.AppType) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetAppType(v)
	})
}

// UpdateAppType sets the "app_type" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateAppType() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateAppType()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *ApplicationUpsertBulk) SetRedirectUris(v []string) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateRedirectUris() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateRedirectUris()
	})
}

// SetAllowedGrants sets the "allowed_grants" field.
func (u *ApplicationUpsertBulk) SetAllowedGrants(v []string) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetAllowedGrants(v)
	})
}

// UpdateAllowedGrants sets the "allowed_grants" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateAllowedGrants() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateAllowedGrants()
	})
}

// SetAllowedResponseTypes sets the "allowed_response_types" field.
func (u *ApplicationUpsertBulk) SetAllowedResponseTypes(v []string) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetAllowedResponseTypes(v)
	})
}

// UpdateAllowedResponseTypes sets the "allowed_response_types" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateAllowedResponseTypes() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateAllowedResponseTypes()
	})
}

// SetAccessTokenTTL sets the "access_token_ttl" field.
func (u *ApplicationUpsertBulk) SetAccessTokenTTL(v int) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetAccessTokenTTL(v)
	})
}

// AddAccessTokenTTL adds v to the "access_token_ttl" field.
func (u *ApplicationUpsertBulk) AddAccessTokenTTL(v int) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.AddAccessTokenTTL(v)
	})
}

// UpdateAccessTokenTTL sets the "access_token_ttl" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateAccessTokenTTL() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateAccessTokenTTL()
	})
}

// SetRefreshTokenTTL sets the "refresh_token_ttl" field.
func (u *ApplicationUpsertBulk) SetRefreshTokenTTL(v int) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetRefreshTokenTTL(v)
	})
}

// AddRefreshTokenTTL adds v to the "refresh_token_ttl" field.
func (u *ApplicationUpsertBulk) AddRefreshTokenTTL(v int) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.AddRefreshTokenTTL(v)
	})
}

// UpdateRefreshTokenTTL sets the "refresh_token_ttl" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateRefreshTokenTTL() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateRefreshTokenTTL()
	})
}

// SetRefreshTokenRotation sets the "refresh_token_rotation" field.
func (u *ApplicationUpsertBulk) SetRefreshTokenRotation(v bool) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetRefreshTokenRotation(v)
	})
}

// UpdateRefreshTokenRotation sets the "refresh_token_rotation" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateRefreshTokenRotation() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateRefreshTokenRotation()
	})
}

// SetFirstParty sets the "first_party" field.
func (u *ApplicationUpsertBulk) SetFirstParty(v bool) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetFirstParty(v)
	})
}

// UpdateFirstParty sets the "first_party" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdateFirstParty() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdateFirstParty()
	})
}

// SetPublic sets the "public" field.
func (u *ApplicationUpsertBulk) SetPublic(v bool) *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.SetPublic(v)
	})
}

// UpdatePublic sets the "public" field to the value that was provided on create.
func (u *ApplicationUpsertBulk) UpdatePublic() *ApplicationUpsertBulk {
	return u.Update(func(s *ApplicationUpsert) {
		s.UpdatePublic()
	})
}

// Exec executes the query.
func (u *ApplicationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ApplicationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ApplicationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ApplicationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
