// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/grokify/systemforge/identity/ent/human"
	"github.com/grokify/systemforge/identity/ent/principal"
)

// HumanCreate is the builder for creating a Human entity.
type HumanCreate struct {
	config
	mutation *HumanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *HumanCreate) SetCreatedAt(v time.Time) *HumanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HumanCreate) SetNillableCreatedAt(v *time.Time) *HumanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HumanCreate) SetUpdatedAt(v time.Time) *HumanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HumanCreate) SetNillableUpdatedAt(v *time.Time) *HumanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPrincipalID sets the "principal_id" field.
func (_c *HumanCreate) SetPrincipalID(v uuid.UUID) *HumanCreate {
	_c.mutation.SetPrincipalID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *HumanCreate) SetEmail(v string) *HumanCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetGivenName sets the "given_name" field.
func (_c *HumanCreate) SetGivenName(v string) *HumanCreate {
	_c.mutation.SetGivenName(v)
	return _c
}

// SetNillableGivenName sets the "given_name" field if the given value is not nil.
func (_c *HumanCreate) SetNillableGivenName(v *string) *HumanCreate {
	if v != nil {
		_c.SetGivenName(*v)
	}
	return _c
}

// SetFamilyName sets the "family_name" field.
func (_c *HumanCreate) SetFamilyName(v string) *HumanCreate {
	_c.mutation.SetFamilyName(v)
	return _c
}

// SetNillableFamilyName sets the "family_name" field if the given value is not nil.
func (_c *HumanCreate) SetNillableFamilyName(v *string) *HumanCreate {
	if v != nil {
		_c.SetFamilyName(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *HumanCreate) SetAvatarURL(v string) *HumanCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *HumanCreate) SetNillableAvatarURL(v *string) *HumanCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetLocale sets the "locale" field.
func (_c *HumanCreate) SetLocale(v string) *HumanCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_c *HumanCreate) SetNillableLocale(v *string) *HumanCreate {
	if v != nil {
		_c.SetLocale(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *HumanCreate) SetTimezone(v string) *HumanCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *HumanCreate) SetNillableTimezone(v *string) *HumanCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetIsPlatformAdmin sets the "is_platform_admin" field.
func (_c *HumanCreate) SetIsPlatformAdmin(v bool) *HumanCreate {
	_c.mutation.SetIsPlatformAdmin(v)
	return _c
}

// SetNillableIsPlatformAdmin sets the "is_platform_admin" field if the given value is not nil.
func (_c *HumanCreate) SetNillableIsPlatformAdmin(v *bool) *HumanCreate {
	if v != nil {
		_c.SetIsPlatformAdmin(*v)
	}
	return _c
}

// SetLastLoginAt sets the "last_login_at" field.
func (_c *HumanCreate) SetLastLoginAt(v time.Time) *HumanCreate {
	_c.mutation.SetLastLoginAt(v)
	return _c
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_c *HumanCreate) SetNillableLastLoginAt(v *time.Time) *HumanCreate {
	if v != nil {
		_c.SetLastLoginAt(*v)
	}
	return _c
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (_c *HumanCreate) SetEmailVerifiedAt(v time.Time) *HumanCreate {
	_c.mutation.SetEmailVerifiedAt(v)
	return _c
}

// SetNillableEmailVerifiedAt sets the "email_verified_at" field if the given value is not nil.
func (_c *HumanCreate) SetNillableEmailVerifiedAt(v *time.Time) *HumanCreate {
	if v != nil {
		_c.SetEmailVerifiedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HumanCreate) SetID(v uuid.UUID) *HumanCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *HumanCreate) SetNillableID(v *uuid.UUID) *HumanCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPrincipal sets the "principal" edge to the Principal entity.
func (_c *HumanCreate) SetPrincipal(v *Principal) *HumanCreate {
	return _c.SetPrincipalID(v.ID)
}

// Mutation returns the HumanMutation object of the builder.
func (_c *HumanCreate) Mutation() *HumanMutation {
	return _c.mutation
}

// Save creates the Human in the database.
func (_c *HumanCreate) Save(ctx context.Context) (*Human, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HumanCreate) SaveX(ctx context.Context) *Human {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HumanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HumanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HumanCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := human.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := human.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Locale(); !ok {
		v := human.DefaultLocale
		_c.mutation.SetLocale(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := human.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.IsPlatformAdmin(); !ok {
		v := human.DefaultIsPlatformAdmin
		_c.mutation.SetIsPlatformAdmin(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := human.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HumanCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Human.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Human.updated_at"`)}
	}
	if _, ok := _c.mutation.PrincipalID(); !ok {
		return &ValidationError{Name: "principal_id", err: errors.New(`ent: missing required field "Human.principal_id"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Human.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := human.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Human.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPlatformAdmin(); !ok {
		return &ValidationError{Name: "is_platform_admin", err: errors.New(`ent: missing required field "Human.is_platform_admin"`)}
	}
	if len(_c.mutation.PrincipalIDs()) == 0 {
		return &ValidationError{Name: "principal", err: errors.New(`ent: missing required edge "Human.principal"`)}
	}
	return nil
}

func (_c *HumanCreate) sqlSave(ctx context.Context) (*Human, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HumanCreate) createSpec() (*Human, *sqlgraph.CreateSpec) {
	var (
		_node = &Human{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(human.Table, sqlgraph.NewFieldSpec(human.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(human.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(human.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(human.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.GivenName(); ok {
		_spec.SetField(human.FieldGivenName, field.TypeString, value)
		_node.GivenName = value
	}
	if value, ok := _c.mutation.FamilyName(); ok {
		_spec.SetField(human.FieldFamilyName, field.TypeString, value)
		_node.FamilyName = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(human.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = &value
	}
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(human.FieldLocale, field.TypeString, value)
		_node.Locale = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(human.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.IsPlatformAdmin(); ok {
		_spec.SetField(human.FieldIsPlatformAdmin, field.TypeBool, value)
		_node.IsPlatformAdmin = value
	}
	if value, ok := _c.mutation.LastLoginAt(); ok {
		_spec.SetField(human.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = &value
	}
	if value, ok := _c.mutation.EmailVerifiedAt(); ok {
		_spec.SetField(human.FieldEmailVerifiedAt, field.TypeTime, value)
		_node.EmailVerifiedAt = &value
	}
	if nodes := _c.mutation.PrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   human.PrincipalTable,
			Columns: []string{human.PrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PrincipalID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Human.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HumanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HumanCreate) OnConflict(opts ...sql.ConflictOption) *HumanUpsertOne {
	_c.conflict = opts
	return &HumanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Human.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HumanCreate) OnConflictColumns(columns ...string) *HumanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HumanUpsertOne{
		create: _c,
	}
}

type (
	// HumanUpsertOne is the builder for "upsert"-ing
	//  one Human node.
	HumanUpsertOne struct {
		create *HumanCreate
	}

	// HumanUpsert is the "OnConflict" setter.
	HumanUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *HumanUpsert) SetUpdatedAt(v time.Time) *HumanUpsert {
	u.Set(human.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HumanUpsert) UpdateUpdatedAt() *HumanUpsert {
	u.SetExcluded(human.FieldUpdatedAt)
	return u
}

// SetEmail sets the "email" field.
func (u *HumanUpsert) SetEmail(v string) *HumanUpsert {
	u.Set(human.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *HumanUpsert) UpdateEmail() *HumanUpsert {
	u.SetExcluded(human.FieldEmail)
	return u
}

// SetGivenName sets the "given_name" field.
func (u *HumanUpsert) SetGivenName(v string) *HumanUpsert {
	u.Set(human.FieldGivenName, v)
	return u
}

// UpdateGivenName sets the "given_name" field to the value that was provided on create.
func (u *HumanUpsert) UpdateGivenName() *HumanUpsert {
	u.SetExcluded(human.FieldGivenName)
	return u
}

// ClearGivenName clears the value of the "given_name" field.
func (u *HumanUpsert) ClearGivenName() *HumanUpsert {
	u.SetNull(human.FieldGivenName)
	return u
}

// SetFamilyName sets the "family_name" field.
func (u *HumanUpsert) SetFamilyName(v string) *HumanUpsert {
	u.Set(human.FieldFamilyName, v)
	return u
}

// UpdateFamilyName sets the "family_name" field to the value that was provided on create.
func (u *HumanUpsert) UpdateFamilyName() *HumanUpsert {
	u.SetExcluded(human.FieldFamilyName)
	return u
}

// ClearFamilyName clears the value of the "family_name" field.
func (u *HumanUpsert) ClearFamilyName() *HumanUpsert {
	u.SetNull(human.FieldFamilyName)
	return u
}

// SetAvatarURL sets the "avatar_url" field.
func (u *HumanUpsert) SetAvatarURL(v string) *HumanUpsert {
	u.Set(human.FieldAvatarURL, v)
	return u
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *HumanUpsert) UpdateAvatarURL() *HumanUpsert {
	u.SetExcluded(human.FieldAvatarURL)
	return u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (u *HumanUpsert) ClearAvatarURL() *HumanUpsert {
	u.SetNull(human.FieldAvatarURL)
	return u
}

// SetLocale sets the "locale" field.
func (u *HumanUpsert) SetLocale(v string) *HumanUpsert {
	u.Set(human.FieldLocale, v)
	return u
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *HumanUpsert) UpdateLocale() *HumanUpsert {
	u.SetExcluded(human.FieldLocale)
	return u
}

// ClearLocale clears the value of the "locale" field.
func (u *HumanUpsert) ClearLocale() *HumanUpsert {
	u.SetNull(human.FieldLocale)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *HumanUpsert) SetTimezone(v string) *HumanUpsert {
	u.Set(human.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *HumanUpsert) UpdateTimezone() *HumanUpsert {
	u.SetExcluded(human.FieldTimezone)
	return u
}

// ClearTimezone clears the value of the "timezone" field.
func (u *HumanUpsert) ClearTimezone() *HumanUpsert {
	u.SetNull(human.FieldTimezone)
	return u
}

// SetIsPlatformAdmin sets the "is_platform_admin" field.
func (u *HumanUpsert) SetIsPlatformAdmin(v bool) *HumanUpsert {
	u.Set(human.FieldIsPlatformAdmin, v)
	return u
}

// UpdateIsPlatformAdmin sets the "is_platform_admin" field to the value that was provided on create.
func (u *HumanUpsert) UpdateIsPlatformAdmin() *HumanUpsert {
	u.SetExcluded(human.FieldIsPlatformAdmin)
	return u
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *HumanUpsert) SetLastLoginAt(v time.Time) *HumanUpsert {
	u.Set(human.FieldLastLoginAt, v)
	return u
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *HumanUpsert) UpdateLastLoginAt() *HumanUpsert {
	u.SetExcluded(human.FieldLastLoginAt)
	return u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *HumanUpsert) ClearLastLoginAt() *HumanUpsert {
	u.SetNull(human.FieldLastLoginAt)
	return u
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (u *HumanUpsert) SetEmailVerifiedAt(v time.Time) *HumanUpsert {
	u.Set(human.FieldEmailVerifiedAt, v)
	return u
}

// UpdateEmailVerifiedAt sets the "email_verified_at" field to the value that was provided on create.
func (u *HumanUpsert) UpdateEmailVerifiedAt() *HumanUpsert {
	u.SetExcluded(human.FieldEmailVerifiedAt)
	return u
}

// ClearEmailVerifiedAt clears the value of the "email_verified_at" field.
func (u *HumanUpsert) ClearEmailVerifiedAt() *HumanUpsert {
	u.SetNull(human.FieldEmailVerifiedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Human.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(human.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HumanUpsertOne) UpdateNewValues() *HumanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(human.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(human.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.PrincipalID(); exists {
			s.SetIgnore(human.FieldPrincipalID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Human.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HumanUpsertOne) Ignore() *HumanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HumanUpsertOne) DoNothing() *HumanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HumanCreate.OnConflict
// documentation for more info.
func (u *HumanUpsertOne) Update(set func(*HumanUpsert)) *HumanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HumanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HumanUpsertOne) SetUpdatedAt(v time.Time) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateUpdatedAt() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmail sets the "email" field.
func (u *HumanUpsertOne) SetEmail(v string) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateEmail() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateEmail()
	})
}

// SetGivenName sets the "given_name" field.
func (u *HumanUpsertOne) SetGivenName(v string) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetGivenName(v)
	})
}

// UpdateGivenName sets the "given_name" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateGivenName() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateGivenName()
	})
}

// ClearGivenName clears the value of the "given_name" field.
func (u *HumanUpsertOne) ClearGivenName() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.ClearGivenName()
	})
}

// SetFamilyName sets the "family_name" field.
func (u *HumanUpsertOne) SetFamilyName(v string) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetFamilyName(v)
	})
}

// UpdateFamilyName sets the "family_name" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateFamilyName() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateFamilyName()
	})
}

// ClearFamilyName clears the value of the "family_name" field.
func (u *HumanUpsertOne) ClearFamilyName() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.ClearFamilyName()
	})
}

// SetAvatarURL sets the "avatar_url" field.
func (u *HumanUpsertOne) SetAvatarURL(v string) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetAvatarURL(v)
	})
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateAvatarURL() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateAvatarURL()
	})
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (u *HumanUpsertOne) ClearAvatarURL() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.ClearAvatarURL()
	})
}

// SetLocale sets the "locale" field.
func (u *HumanUpsertOne) SetLocale(v string) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetLocale(v)
	})
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateLocale() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateLocale()
	})
}

// ClearLocale clears the value of the "locale" field.
func (u *HumanUpsertOne) ClearLocale() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.ClearLocale()
	})
}

// SetTimezone sets the "timezone" field.
func (u *HumanUpsertOne) SetTimezone(v string) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateTimezone() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateTimezone()
	})
}

// ClearTimezone clears the value of the "timezone" field.
func (u *HumanUpsertOne) ClearTimezone() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.ClearTimezone()
	})
}

// SetIsPlatformAdmin sets the "is_platform_admin" field.
func (u *HumanUpsertOne) SetIsPlatformAdmin(v bool) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetIsPlatformAdmin(v)
	})
}

// UpdateIsPlatformAdmin sets the "is_platform_admin" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateIsPlatformAdmin() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateIsPlatformAdmin()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *HumanUpsertOne) SetLastLoginAt(v time.Time) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateLastLoginAt() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *HumanUpsertOne) ClearLastLoginAt() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.ClearLastLoginAt()
	})
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (u *HumanUpsertOne) SetEmailVerifiedAt(v time.Time) *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.SetEmailVerifiedAt(v)
	})
}

// UpdateEmailVerifiedAt sets the "email_verified_at" field to the value that was provided on create.
func (u *HumanUpsertOne) UpdateEmailVerifiedAt() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateEmailVerifiedAt()
	})
}

// ClearEmailVerifiedAt clears the value of the "email_verified_at" field.
func (u *HumanUpsertOne) ClearEmailVerifiedAt() *HumanUpsertOne {
	return u.Update(func(s *HumanUpsert) {
		s.ClearEmailVerifiedAt()
	})
}

// Exec executes the query.
func (u *HumanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HumanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HumanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HumanUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: HumanUpsertOne.ID is not supported by MySQL driver. Use HumanUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HumanUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HumanCreateBulk is the builder for creating many Human entities in bulk.
type HumanCreateBulk struct {
	config
	err      error
	builders []*HumanCreate
	conflict []sql.ConflictOption
}

// Save creates the Human entities in the database.
func (_c *HumanCreateBulk) Save(ctx context.Context) ([]*Human, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Human, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HumanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HumanCreateBulk) SaveX(ctx context.Context) []*Human {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HumanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HumanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Human.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HumanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *HumanCreateBulk) OnConflict(opts ...sql.ConflictOption) *HumanUpsertBulk {
	_c.conflict = opts
	return &HumanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Human.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HumanCreateBulk) OnConflictColumns(columns ...string) *HumanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HumanUpsertBulk{
		create: _c,
	}
}

// HumanUpsertBulk is the builder for "upsert"-ing
// a bulk of Human nodes.
type HumanUpsertBulk struct {
	create *HumanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Human.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(human.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HumanUpsertBulk) UpdateNewValues() *HumanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(human.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(human.FieldCreatedAt)
			}
			if _, exists := b.mutation.PrincipalID(); exists {
				s.SetIgnore(human.FieldPrincipalID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Human.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HumanUpsertBulk) Ignore() *HumanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HumanUpsertBulk) DoNothing() *HumanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HumanCreateBulk.OnConflict
// documentation for more info.
func (u *HumanUpsertBulk) Update(set func(*HumanUpsert)) *HumanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HumanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HumanUpsertBulk) SetUpdatedAt(v time.Time) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateUpdatedAt() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmail sets the "email" field.
func (u *HumanUpsertBulk) SetEmail(v string) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateEmail() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateEmail()
	})
}

// SetGivenName sets the "given_name" field.
func (u *HumanUpsertBulk) SetGivenName(v string) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetGivenName(v)
	})
}

// UpdateGivenName sets the "given_name" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateGivenName() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateGivenName()
	})
}

// ClearGivenName clears the value of the "given_name" field.
func (u *HumanUpsertBulk) ClearGivenName() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.ClearGivenName()
	})
}

// SetFamilyName sets the "family_name" field.
func (u *HumanUpsertBulk) SetFamilyName(v string) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetFamilyName(v)
	})
}

// UpdateFamilyName sets the "family_name" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateFamilyName() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateFamilyName()
	})
}

// ClearFamilyName clears the value of the "family_name" field.
func (u *HumanUpsertBulk) ClearFamilyName() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.ClearFamilyName()
	})
}

// SetAvatarURL sets the "avatar_url" field.
func (u *HumanUpsertBulk) SetAvatarURL(v string) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetAvatarURL(v)
	})
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateAvatarURL() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateAvatarURL()
	})
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (u *HumanUpsertBulk) ClearAvatarURL() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.ClearAvatarURL()
	})
}

// SetLocale sets the "locale" field.
func (u *HumanUpsertBulk) SetLocale(v string) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetLocale(v)
	})
}

// UpdateLocale sets the "locale" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateLocale() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateLocale()
	})
}

// ClearLocale clears the value of the "locale" field.
func (u *HumanUpsertBulk) ClearLocale() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.ClearLocale()
	})
}

// SetTimezone sets the "timezone" field.
func (u *HumanUpsertBulk) SetTimezone(v string) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateTimezone() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateTimezone()
	})
}

// ClearTimezone clears the value of the "timezone" field.
func (u *HumanUpsertBulk) ClearTimezone() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.ClearTimezone()
	})
}

// SetIsPlatformAdmin sets the "is_platform_admin" field.
func (u *HumanUpsertBulk) SetIsPlatformAdmin(v bool) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetIsPlatformAdmin(v)
	})
}

// UpdateIsPlatformAdmin sets the "is_platform_admin" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateIsPlatformAdmin() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateIsPlatformAdmin()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *HumanUpsertBulk) SetLastLoginAt(v time.Time) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateLastLoginAt() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *HumanUpsertBulk) ClearLastLoginAt() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.ClearLastLoginAt()
	})
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (u *HumanUpsertBulk) SetEmailVerifiedAt(v time.Time) *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.SetEmailVerifiedAt(v)
	})
}

// UpdateEmailVerifiedAt sets the "email_verified_at" field to the value that was provided on create.
func (u *HumanUpsertBulk) UpdateEmailVerifiedAt() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.UpdateEmailVerifiedAt()
	})
}

// ClearEmailVerifiedAt clears the value of the "email_verified_at" field.
func (u *HumanUpsertBulk) ClearEmailVerifiedAt() *HumanUpsertBulk {
	return u.Update(func(s *HumanUpsert) {
		s.ClearEmailVerifiedAt()
	})
}

// Exec executes the query.
func (u *HumanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HumanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HumanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HumanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
