// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/grokify/coreforge/identity/ent/invite"
	"github.com/grokify/coreforge/identity/ent/organization"
	"github.com/grokify/coreforge/identity/ent/principal"
)

// InviteCreate is the builder for creating a Invite entity.
type InviteCreate struct {
	config
	mutation *InviteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *InviteCreate) SetCreatedAt(v time.Time) *InviteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InviteCreate) SetNillableCreatedAt(v *time.Time) *InviteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InviteCreate) SetUpdatedAt(v time.Time) *InviteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InviteCreate) SetNillableUpdatedAt(v *time.Time) *InviteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *InviteCreate) SetOrganizationID(v uuid.UUID) *InviteCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetInviterPrincipalID sets the "inviter_principal_id" field.
func (_c *InviteCreate) SetInviterPrincipalID(v uuid.UUID) *InviteCreate {
	_c.mutation.SetInviterPrincipalID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *InviteCreate) SetEmail(v string) *InviteCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *InviteCreate) SetRole(v string) *InviteCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *InviteCreate) SetNillableRole(v *string) *InviteCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetToken sets the "token" field.
func (_c *InviteCreate) SetToken(v string) *InviteCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InviteCreate) SetStatus(v invite.Status) *InviteCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InviteCreate) SetNillableStatus(v *invite.Status) *InviteCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *InviteCreate) SetMessage(v string) *InviteCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *InviteCreate) SetNillableMessage(v *string) *InviteCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *InviteCreate) SetExpiresAt(v time.Time) *InviteCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetAcceptedAt sets the "accepted_at" field.
func (_c *InviteCreate) SetAcceptedAt(v time.Time) *InviteCreate {
	_c.mutation.SetAcceptedAt(v)
	return _c
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_c *InviteCreate) SetNillableAcceptedAt(v *time.Time) *InviteCreate {
	if v != nil {
		_c.SetAcceptedAt(*v)
	}
	return _c
}

// SetAcceptedByPrincipalID sets the "accepted_by_principal_id" field.
func (_c *InviteCreate) SetAcceptedByPrincipalID(v uuid.UUID) *InviteCreate {
	_c.mutation.SetAcceptedByPrincipalID(v)
	return _c
}

// SetNillableAcceptedByPrincipalID sets the "accepted_by_principal_id" field if the given value is not nil.
func (_c *InviteCreate) SetNillableAcceptedByPrincipalID(v *uuid.UUID) *InviteCreate {
	if v != nil {
		_c.SetAcceptedByPrincipalID(*v)
	}
	return _c
}

// SetResendCount sets the "resend_count" field.
func (_c *InviteCreate) SetResendCount(v int) *InviteCreate {
	_c.mutation.SetResendCount(v)
	return _c
}

// SetNillableResendCount sets the "resend_count" field if the given value is not nil.
func (_c *InviteCreate) SetNillableResendCount(v *int) *InviteCreate {
	if v != nil {
		_c.SetResendCount(*v)
	}
	return _c
}

// SetLastSentAt sets the "last_sent_at" field.
func (_c *InviteCreate) SetLastSentAt(v time.Time) *InviteCreate {
	_c.mutation.SetLastSentAt(v)
	return _c
}

// SetNillableLastSentAt sets the "last_sent_at" field if the given value is not nil.
func (_c *InviteCreate) SetNillableLastSentAt(v *time.Time) *InviteCreate {
	if v != nil {
		_c.SetLastSentAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InviteCreate) SetID(v uuid.UUID) *InviteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InviteCreate) SetNillableID(v *uuid.UUID) *InviteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *InviteCreate) SetOrganization(v *Organization) *InviteCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetInviterID sets the "inviter" edge to the Principal entity by ID.
func (_c *InviteCreate) SetInviterID(id uuid.UUID) *InviteCreate {
	_c.mutation.SetInviterID(id)
	return _c
}

// SetInviter sets the "inviter" edge to the Principal entity.
func (_c *InviteCreate) SetInviter(v *Principal) *InviteCreate {
	return _c.SetInviterID(v.ID)
}

// Mutation returns the InviteMutation object of the builder.
func (_c *InviteCreate) Mutation() *InviteMutation {
	return _c.mutation
}

// Save creates the Invite in the database.
func (_c *InviteCreate) Save(ctx context.Context) (*Invite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InviteCreate) SaveX(ctx context.Context) *Invite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InviteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invite.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invite.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := invite.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invite.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ResendCount(); !ok {
		v := invite.DefaultResendCount
		_c.mutation.SetResendCount(v)
	}
	if _, ok := _c.mutation.LastSentAt(); !ok {
		v := invite.DefaultLastSentAt()
		_c.mutation.SetLastSentAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := invite.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InviteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Invite.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Invite.updated_at"`)}
	}
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "Invite.organization_id"`)}
	}
	if _, ok := _c.mutation.InviterPrincipalID(); !ok {
		return &ValidationError{Name: "inviter_principal_id", err: errors.New(`ent: missing required field "Invite.inviter_principal_id"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Invite.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := invite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Invite.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Invite.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := invite.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Invite.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Invite.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := invite.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Invite.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Invite.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invite.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invite.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Invite.expires_at"`)}
	}
	if _, ok := _c.mutation.ResendCount(); !ok {
		return &ValidationError{Name: "resend_count", err: errors.New(`ent: missing required field "Invite.resend_count"`)}
	}
	if _, ok := _c.mutation.LastSentAt(); !ok {
		return &ValidationError{Name: "last_sent_at", err: errors.New(`ent: missing required field "Invite.last_sent_at"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "Invite.organization"`)}
	}
	if len(_c.mutation.InviterIDs()) == 0 {
		return &ValidationError{Name: "inviter", err: errors.New(`ent: missing required edge "Invite.inviter"`)}
	}
	return nil
}

func (_c *InviteCreate) sqlSave(ctx context.Context) (*Invite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InviteCreate) createSpec() (*Invite, *sqlgraph.CreateSpec) {
	var (
		_node = &Invite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invite.Table, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invite.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(invite.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(invite.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(invite.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invite.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(invite.FieldMessage, field.TypeString, value)
		_node.Message = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(invite.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.AcceptedAt(); ok {
		_spec.SetField(invite.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = &value
	}
	if value, ok := _c.mutation.AcceptedByPrincipalID(); ok {
		_spec.SetField(invite.FieldAcceptedByPrincipalID, field.TypeUUID, value)
		_node.AcceptedByPrincipalID = &value
	}
	if value, ok := _c.mutation.ResendCount(); ok {
		_spec.SetField(invite.FieldResendCount, field.TypeInt, value)
		_node.ResendCount = value
	}
	if value, ok := _c.mutation.LastSentAt(); ok {
		_spec.SetField(invite.FieldLastSentAt, field.TypeTime, value)
		_node.LastSentAt = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.OrganizationTable,
			Columns: []string{invite.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InviterTable,
			Columns: []string{invite.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviterPrincipalID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invite.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteCreate) OnConflict(opts ...sql.ConflictOption) *InviteUpsertOne {
	_c.conflict = opts
	return &InviteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteCreate) OnConflictColumns(columns ...string) *InviteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteUpsertOne{
		create: _c,
	}
}

type (
	// InviteUpsertOne is the builder for "upsert"-ing
	//  one Invite node.
	InviteUpsertOne struct {
		create *InviteCreate
	}

	// InviteUpsert is the "OnConflict" setter.
	InviteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *InviteUpsert) SetUpdatedAt(v time.Time) *InviteUpsert {
	u.Set(invite.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InviteUpsert) UpdateUpdatedAt() *InviteUpsert {
	u.SetExcluded(invite.FieldUpdatedAt)
	return u
}

// SetOrganizationID sets the "organization_id" field.
func (u *InviteUpsert) SetOrganizationID(v uuid.UUID) *InviteUpsert {
	u.Set(invite.FieldOrganizationID, v)
	return u
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *InviteUpsert) UpdateOrganizationID() *InviteUpsert {
	u.SetExcluded(invite.FieldOrganizationID)
	return u
}

// SetInviterPrincipalID sets the "inviter_principal_id" field.
func (u *InviteUpsert) SetInviterPrincipalID(v uuid.UUID) *InviteUpsert {
	u.Set(invite.FieldInviterPrincipalID, v)
	return u
}

// UpdateInviterPrincipalID sets the "inviter_principal_id" field to the value that was provided on create.
func (u *InviteUpsert) UpdateInviterPrincipalID() *InviteUpsert {
	u.SetExcluded(invite.FieldInviterPrincipalID)
	return u
}

// SetEmail sets the "email" field.
func (u *InviteUpsert) SetEmail(v string) *InviteUpsert {
	u.Set(invite.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InviteUpsert) UpdateEmail() *InviteUpsert {
	u.SetExcluded(invite.FieldEmail)
	return u
}

// SetRole sets the "role" field.
func (u *InviteUpsert) SetRole(v string) *InviteUpsert {
	u.Set(invite.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *InviteUpsert) UpdateRole() *InviteUpsert {
	u.SetExcluded(invite.FieldRole)
	return u
}

// SetToken sets the "token" field.
func (u *InviteUpsert) SetToken(v string) *InviteUpsert {
	u.Set(invite.FieldToken, v)
	return u
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *InviteUpsert) UpdateToken() *InviteUpsert {
	u.SetExcluded(invite.FieldToken)
	return u
}

// SetStatus sets the "status" field.
func (u *InviteUpsert) SetStatus(v invite.Status) *InviteUpsert {
	u.Set(invite.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InviteUpsert) UpdateStatus() *InviteUpsert {
	u.SetExcluded(invite.FieldStatus)
	return u
}

// SetMessage sets the "message" field.
func (u *InviteUpsert) SetMessage(v string) *InviteUpsert {
	u.Set(invite.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *InviteUpsert) UpdateMessage() *InviteUpsert {
	u.SetExcluded(invite.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *InviteUpsert) ClearMessage() *InviteUpsert {
	u.SetNull(invite.FieldMessage)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *InviteUpsert) SetExpiresAt(v time.Time) *InviteUpsert {
	u.Set(invite.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *InviteUpsert) UpdateExpiresAt() *InviteUpsert {
	u.SetExcluded(invite.FieldExpiresAt)
	return u
}

// SetAcceptedAt sets the "accepted_at" field.
func (u *InviteUpsert) SetAcceptedAt(v time.Time) *InviteUpsert {
	u.Set(invite.FieldAcceptedAt, v)
	return u
}

// UpdateAcceptedAt sets the "accepted_at" field to the value that was provided on create.
func (u *InviteUpsert) UpdateAcceptedAt() *InviteUpsert {
	u.SetExcluded(invite.FieldAcceptedAt)
	return u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (u *InviteUpsert) ClearAcceptedAt() *InviteUpsert {
	u.SetNull(invite.FieldAcceptedAt)
	return u
}

// SetAcceptedByPrincipalID sets the "accepted_by_principal_id" field.
func (u *InviteUpsert) SetAcceptedByPrincipalID(v uuid.UUID) *InviteUpsert {
	u.Set(invite.FieldAcceptedByPrincipalID, v)
	return u
}

// UpdateAcceptedByPrincipalID sets the "accepted_by_principal_id" field to the value that was provided on create.
func (u *InviteUpsert) UpdateAcceptedByPrincipalID() *InviteUpsert {
	u.SetExcluded(invite.FieldAcceptedByPrincipalID)
	return u
}

// ClearAcceptedByPrincipalID clears the value of the "accepted_by_principal_id" field.
func (u *InviteUpsert) ClearAcceptedByPrincipalID() *InviteUpsert {
	u.SetNull(invite.FieldAcceptedByPrincipalID)
	return u
}

// SetResendCount sets the "resend_count" field.
func (u *InviteUpsert) SetResendCount(v int) *InviteUpsert {
	u.Set(invite.FieldResendCount, v)
	return u
}

// UpdateResendCount sets the "resend_count" field to the value that was provided on create.
func (u *InviteUpsert) UpdateResendCount() *InviteUpsert {
	u.SetExcluded(invite.FieldResendCount)
	return u
}

// AddResendCount adds v to the "resend_count" field.
func (u *InviteUpsert) AddResendCount(v int) *InviteUpsert {
	u.Add(invite.FieldResendCount, v)
	return u
}

// SetLastSentAt sets the "last_sent_at" field.
func (u *InviteUpsert) SetLastSentAt(v time.Time) *InviteUpsert {
	u.Set(invite.FieldLastSentAt, v)
	return u
}

// UpdateLastSentAt sets the "last_sent_at" field to the value that was provided on create.
func (u *InviteUpsert) UpdateLastSentAt() *InviteUpsert {
	u.SetExcluded(invite.FieldLastSentAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(invite.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InviteUpsertOne) UpdateNewValues() *InviteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(invite.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invite.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invite.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InviteUpsertOne) Ignore() *InviteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteUpsertOne) DoNothing() *InviteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteCreate.OnConflict
// documentation for more info.
func (u *InviteUpsertOne) Update(set func(*InviteUpsert)) *InviteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InviteUpsertOne) SetUpdatedAt(v time.Time) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateUpdatedAt() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrganizationID sets the "organization_id" field.
func (u *InviteUpsertOne) SetOrganizationID(v uuid.UUID) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateOrganizationID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetInviterPrincipalID sets the "inviter_principal_id" field.
func (u *InviteUpsertOne) SetInviterPrincipalID(v uuid.UUID) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetInviterPrincipalID(v)
	})
}

// UpdateInviterPrincipalID sets the "inviter_principal_id" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateInviterPrincipalID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateInviterPrincipalID()
	})
}

// SetEmail sets the "email" field.
func (u *InviteUpsertOne) SetEmail(v string) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateEmail() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateEmail()
	})
}

// SetRole sets the "role" field.
func (u *InviteUpsertOne) SetRole(v string) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateRole() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateRole()
	})
}

// SetToken sets the "token" field.
func (u *InviteUpsertOne) SetToken(v string) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateToken() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateToken()
	})
}

// SetStatus sets the "status" field.
func (u *InviteUpsertOne) SetStatus(v invite.Status) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateStatus() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *InviteUpsertOne) SetMessage(v string) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateMessage() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *InviteUpsertOne) ClearMessage() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.ClearMessage()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *InviteUpsertOne) SetExpiresAt(v time.Time) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateExpiresAt() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAcceptedAt sets the "accepted_at" field.
func (u *InviteUpsertOne) SetAcceptedAt(v time.Time) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetAcceptedAt(v)
	})
}

// UpdateAcceptedAt sets the "accepted_at" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateAcceptedAt() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateAcceptedAt()
	})
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (u *InviteUpsertOne) ClearAcceptedAt() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.ClearAcceptedAt()
	})
}

// SetAcceptedByPrincipalID sets the "accepted_by_principal_id" field.
func (u *InviteUpsertOne) SetAcceptedByPrincipalID(v uuid.UUID) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetAcceptedByPrincipalID(v)
	})
}

// UpdateAcceptedByPrincipalID sets the "accepted_by_principal_id" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateAcceptedByPrincipalID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateAcceptedByPrincipalID()
	})
}

// ClearAcceptedByPrincipalID clears the value of the "accepted_by_principal_id" field.
func (u *InviteUpsertOne) ClearAcceptedByPrincipalID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.ClearAcceptedByPrincipalID()
	})
}

// SetResendCount sets the "resend_count" field.
func (u *InviteUpsertOne) SetResendCount(v int) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetResendCount(v)
	})
}

// AddResendCount adds v to the "resend_count" field.
func (u *InviteUpsertOne) AddResendCount(v int) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.AddResendCount(v)
	})
}

// UpdateResendCount sets the "resend_count" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateResendCount() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateResendCount()
	})
}

// SetLastSentAt sets the "last_sent_at" field.
func (u *InviteUpsertOne) SetLastSentAt(v time.Time) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetLastSentAt(v)
	})
}

// UpdateLastSentAt sets the "last_sent_at" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateLastSentAt() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateLastSentAt()
	})
}

// Exec executes the query.
func (u *InviteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InviteUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: InviteUpsertOne.ID is not supported by MySQL driver. Use InviteUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InviteUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InviteCreateBulk is the builder for creating many Invite entities in bulk.
type InviteCreateBulk struct {
	config
	err      error
	builders []*InviteCreate
	conflict []sql.ConflictOption
}

// Save creates the Invite entities in the database.
func (_c *InviteCreateBulk) Save(ctx context.Context) ([]*Invite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Invite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InviteCreateBulk) SaveX(ctx context.Context) []*Invite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invite.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteCreateBulk) OnConflict(opts ...sql.ConflictOption) *InviteUpsertBulk {
	_c.conflict = opts
	return &InviteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteCreateBulk) OnConflictColumns(columns ...string) *InviteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteUpsertBulk{
		create: _c,
	}
}

// InviteUpsertBulk is the builder for "upsert"-ing
// a bulk of Invite nodes.
type InviteUpsertBulk struct {
	create *InviteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(invite.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InviteUpsertBulk) UpdateNewValues() *InviteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(invite.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invite.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InviteUpsertBulk) Ignore() *InviteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteUpsertBulk) DoNothing() *InviteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteCreateBulk.OnConflict
// documentation for more info.
func (u *InviteUpsertBulk) Update(set func(*InviteUpsert)) *InviteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InviteUpsertBulk) SetUpdatedAt(v time.Time) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateUpdatedAt() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrganizationID sets the "organization_id" field.
func (u *InviteUpsertBulk) SetOrganizationID(v uuid.UUID) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetOrganizationID(v)
	})
}

// UpdateOrganizationID sets the "organization_id" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateOrganizationID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateOrganizationID()
	})
}

// SetInviterPrincipalID sets the "inviter_principal_id" field.
func (u *InviteUpsertBulk) SetInviterPrincipalID(v uuid.UUID) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetInviterPrincipalID(v)
	})
}

// UpdateInviterPrincipalID sets the "inviter_principal_id" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateInviterPrincipalID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateInviterPrincipalID()
	})
}

// SetEmail sets the "email" field.
func (u *InviteUpsertBulk) SetEmail(v string) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateEmail() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateEmail()
	})
}

// SetRole sets the "role" field.
func (u *InviteUpsertBulk) SetRole(v string) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateRole() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateRole()
	})
}

// SetToken sets the "token" field.
func (u *InviteUpsertBulk) SetToken(v string) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateToken() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateToken()
	})
}

// SetStatus sets the "status" field.
func (u *InviteUpsertBulk) SetStatus(v invite.Status) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateStatus() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *InviteUpsertBulk) SetMessage(v string) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateMessage() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *InviteUpsertBulk) ClearMessage() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.ClearMessage()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *InviteUpsertBulk) SetExpiresAt(v time.Time) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateExpiresAt() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetAcceptedAt sets the "accepted_at" field.
func (u *InviteUpsertBulk) SetAcceptedAt(v time.Time) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetAcceptedAt(v)
	})
}

// UpdateAcceptedAt sets the "accepted_at" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateAcceptedAt() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateAcceptedAt()
	})
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (u *InviteUpsertBulk) ClearAcceptedAt() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.ClearAcceptedAt()
	})
}

// SetAcceptedByPrincipalID sets the "accepted_by_principal_id" field.
func (u *InviteUpsertBulk) SetAcceptedByPrincipalID(v uuid.UUID) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetAcceptedByPrincipalID(v)
	})
}

// UpdateAcceptedByPrincipalID sets the "accepted_by_principal_id" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateAcceptedByPrincipalID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateAcceptedByPrincipalID()
	})
}

// ClearAcceptedByPrincipalID clears the value of the "accepted_by_principal_id" field.
func (u *InviteUpsertBulk) ClearAcceptedByPrincipalID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.ClearAcceptedByPrincipalID()
	})
}

// SetResendCount sets the "resend_count" field.
func (u *InviteUpsertBulk) SetResendCount(v int) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetResendCount(v)
	})
}

// AddResendCount adds v to the "resend_count" field.
func (u *InviteUpsertBulk) AddResendCount(v int) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.AddResendCount(v)
	})
}

// UpdateResendCount sets the "resend_count" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateResendCount() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateResendCount()
	})
}

// SetLastSentAt sets the "last_sent_at" field.
func (u *InviteUpsertBulk) SetLastSentAt(v time.Time) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetLastSentAt(v)
	})
}

// UpdateLastSentAt sets the "last_sent_at" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateLastSentAt() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateLastSentAt()
	})
}

// Exec executes the query.
func (u *InviteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InviteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
