// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/grokify/systemforge/identity/ent/oauthapp"
	"github.com/grokify/systemforge/identity/ent/oauthappsecret"
)

// OAuthAppSecret is the model entity for the OAuthAppSecret schema.
type OAuthAppSecret struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OAuth app this secret belongs to
	AppID uuid.UUID `json:"app_id,omitempty"`
	// Argon2id hash of the secret
	SecretHash string `json:"-"`
	// First few chars for identification
	SecretPrefix string `json:"secret_prefix,omitempty"`
	// When this secret expires
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// Revoked holds the value of the "revoked" field.
	Revoked bool `json:"revoked,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OAuthAppSecretQuery when eager-loading is set.
	Edges        OAuthAppSecretEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OAuthAppSecretEdges holds the relations/edges for other nodes in the graph.
type OAuthAppSecretEdges struct {
	// App holds the value of the app edge.
	App *OAuthApp `json:"app,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AppOrErr returns the App value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthAppSecretEdges) AppOrErr() (*OAuthApp, error) {
	if e.App != nil {
		return e.App, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: oauthapp.Label}
	}
	return nil, &NotLoadedError{edge: "app"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthAppSecret) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthappsecret.FieldRevoked:
			values[i] = new(sql.NullBool)
		case oauthappsecret.FieldSecretHash, oauthappsecret.FieldSecretPrefix:
			values[i] = new(sql.NullString)
		case oauthappsecret.FieldExpiresAt, oauthappsecret.FieldLastUsedAt, oauthappsecret.FieldRevokedAt, oauthappsecret.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case oauthappsecret.FieldID, oauthappsecret.FieldAppID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthAppSecret fields.
func (_m *OAuthAppSecret) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthappsecret.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case oauthappsecret.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				_m.AppID = *value
			}
		case oauthappsecret.FieldSecretHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_hash", values[i])
			} else if value.Valid {
				_m.SecretHash = value.String
			}
		case oauthappsecret.FieldSecretPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_prefix", values[i])
			} else if value.Valid {
				_m.SecretPrefix = value.String
			}
		case oauthappsecret.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case oauthappsecret.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case oauthappsecret.FieldRevoked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field revoked", values[i])
			} else if value.Valid {
				_m.Revoked = value.Bool
			}
		case oauthappsecret.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case oauthappsecret.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthAppSecret.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthAppSecret) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryApp queries the "app" edge of the OAuthAppSecret entity.
func (_m *OAuthAppSecret) QueryApp() *OAuthAppQuery {
	return NewOAuthAppSecretClient(_m.config).QueryApp(_m)
}

// Update returns a builder for updating this OAuthAppSecret.
// Note that you need to call OAuthAppSecret.Unwrap() before calling this method if this OAuthAppSecret
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthAppSecret) Update() *OAuthAppSecretUpdateOne {
	return NewOAuthAppSecretClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthAppSecret entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthAppSecret) Unwrap() *OAuthAppSecret {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthAppSecret is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthAppSecret) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthAppSecret(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppID))
	builder.WriteString(", ")
	builder.WriteString("secret_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("secret_prefix=")
	builder.WriteString(_m.SecretPrefix)
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("revoked=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revoked))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthAppSecrets is a parsable slice of OAuthAppSecret.
type OAuthAppSecrets []*OAuthAppSecret
