// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/grokify/systemforge/identity/ent/oauthapp"
	"github.com/grokify/systemforge/identity/ent/organization"
	"github.com/grokify/systemforge/identity/ent/user"
)

// OAuthApp is the model entity for the OAuthApp schema.
type OAuthApp struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Public client identifier
	ClientID string `json:"client_id,omitempty"`
	// Human-readable app name
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// LogoURL holds the value of the "logo_url" field.
	LogoURL string `json:"logo_url,omitempty"`
	// web=confidential, spa/native=public+PKCE, service/machine=client_credentials
	AppType oauthapp.AppType `json:"app_type,omitempty"`
	// User who created this app
	OwnerID uuid.UUID `json:"owner_id,omitempty"`
	// Organization scope (optional)
	OrganizationID *uuid.UUID `json:"organization_id,omitempty"`
	// Allowed redirect URIs
	RedirectUris []string `json:"redirect_uris,omitempty"`
	// Scopes this app can request
	AllowedScopes []string `json:"allowed_scopes,omitempty"`
	// Allowed grant types
	AllowedGrants []string `json:"allowed_grants,omitempty"`
	// Allowed response types
	AllowedResponseTypes []string `json:"allowed_response_types,omitempty"`
	// Access token TTL in seconds (default 15 min)
	AccessTokenTTL int `json:"access_token_ttl,omitempty"`
	// Refresh token TTL in seconds (default 7 days)
	RefreshTokenTTL int `json:"refresh_token_ttl,omitempty"`
	// Rotate refresh tokens on use
	RefreshTokenRotation bool `json:"refresh_token_rotation,omitempty"`
	// First-party apps skip consent screen
	FirstParty bool `json:"first_party,omitempty"`
	// Public clients cannot keep secrets
	Public bool `json:"public,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Custom metadata
	Metadata map[string]string `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OAuthAppQuery when eager-loading is set.
	Edges        OAuthAppEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OAuthAppEdges holds the relations/edges for other nodes in the graph.
type OAuthAppEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// Secrets holds the value of the secrets edge.
	Secrets []*OAuthAppSecret `json:"secrets,omitempty"`
	// Tokens holds the value of the tokens edge.
	Tokens []*OAuthToken `json:"tokens,omitempty"`
	// AuthCodes holds the value of the auth_codes edge.
	AuthCodes []*OAuthAuthCode `json:"auth_codes,omitempty"`
	// Consents holds the value of the consents edge.
	Consents []*OAuthConsent `json:"consents,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthAppEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthAppEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// SecretsOrErr returns the Secrets value or an error if the edge
// was not loaded in eager-loading.
func (e OAuthAppEdges) SecretsOrErr() ([]*OAuthAppSecret, error) {
	if e.loadedTypes[2] {
		return e.Secrets, nil
	}
	return nil, &NotLoadedError{edge: "secrets"}
}

// TokensOrErr returns the Tokens value or an error if the edge
// was not loaded in eager-loading.
func (e OAuthAppEdges) TokensOrErr() ([]*OAuthToken, error) {
	if e.loadedTypes[3] {
		return e.Tokens, nil
	}
	return nil, &NotLoadedError{edge: "tokens"}
}

// AuthCodesOrErr returns the AuthCodes value or an error if the edge
// was not loaded in eager-loading.
func (e OAuthAppEdges) AuthCodesOrErr() ([]*OAuthAuthCode, error) {
	if e.loadedTypes[4] {
		return e.AuthCodes, nil
	}
	return nil, &NotLoadedError{edge: "auth_codes"}
}

// ConsentsOrErr returns the Consents value or an error if the edge
// was not loaded in eager-loading.
func (e OAuthAppEdges) ConsentsOrErr() ([]*OAuthConsent, error) {
	if e.loadedTypes[5] {
		return e.Consents, nil
	}
	return nil, &NotLoadedError{edge: "consents"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthApp) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthapp.FieldOrganizationID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case oauthapp.FieldRedirectUris, oauthapp.FieldAllowedScopes, oauthapp.FieldAllowedGrants, oauthapp.FieldAllowedResponseTypes, oauthapp.FieldMetadata:
			values[i] = new([]byte)
		case oauthapp.FieldRefreshTokenRotation, oauthapp.FieldFirstParty, oauthapp.FieldPublic, oauthapp.FieldActive:
			values[i] = new(sql.NullBool)
		case oauthapp.FieldAccessTokenTTL, oauthapp.FieldRefreshTokenTTL:
			values[i] = new(sql.NullInt64)
		case oauthapp.FieldClientID, oauthapp.FieldName, oauthapp.FieldDescription, oauthapp.FieldLogoURL, oauthapp.FieldAppType:
			values[i] = new(sql.NullString)
		case oauthapp.FieldRevokedAt, oauthapp.FieldCreatedAt, oauthapp.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case oauthapp.FieldID, oauthapp.FieldOwnerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthApp fields.
func (_m *OAuthApp) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthapp.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case oauthapp.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oauthapp.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case oauthapp.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case oauthapp.FieldLogoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo_url", values[i])
			} else if value.Valid {
				_m.LogoURL = value.String
			}
		case oauthapp.FieldAppType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_type", values[i])
			} else if value.Valid {
				_m.AppType = oauthapp.AppType(value.String)
			}
		case oauthapp.FieldOwnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value != nil {
				_m.OwnerID = *value
			}
		case oauthapp.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = new(uuid.UUID)
				*_m.OrganizationID = *value.S.(*uuid.UUID)
			}
		case oauthapp.FieldRedirectUris:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_uris", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RedirectUris); err != nil {
					return fmt.Errorf("unmarshal field redirect_uris: %w", err)
				}
			}
		case oauthapp.FieldAllowedScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedScopes); err != nil {
					return fmt.Errorf("unmarshal field allowed_scopes: %w", err)
				}
			}
		case oauthapp.FieldAllowedGrants:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_grants", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedGrants); err != nil {
					return fmt.Errorf("unmarshal field allowed_grants: %w", err)
				}
			}
		case oauthapp.FieldAllowedResponseTypes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_response_types", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedResponseTypes); err != nil {
					return fmt.Errorf("unmarshal field allowed_response_types: %w", err)
				}
			}
		case oauthapp.FieldAccessTokenTTL:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field access_token_ttl", values[i])
			} else if value.Valid {
				_m.AccessTokenTTL = int(value.Int64)
			}
		case oauthapp.FieldRefreshTokenTTL:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token_ttl", values[i])
			} else if value.Valid {
				_m.RefreshTokenTTL = int(value.Int64)
			}
		case oauthapp.FieldRefreshTokenRotation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token_rotation", values[i])
			} else if value.Valid {
				_m.RefreshTokenRotation = value.Bool
			}
		case oauthapp.FieldFirstParty:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field first_party", values[i])
			} else if value.Valid {
				_m.FirstParty = value.Bool
			}
		case oauthapp.FieldPublic:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field public", values[i])
			} else if value.Valid {
				_m.Public = value.Bool
			}
		case oauthapp.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case oauthapp.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case oauthapp.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case oauthapp.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthapp.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthApp.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthApp) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the OAuthApp entity.
func (_m *OAuthApp) QueryOwner() *UserQuery {
	return NewOAuthAppClient(_m.config).QueryOwner(_m)
}

// QueryOrganization queries the "organization" edge of the OAuthApp entity.
func (_m *OAuthApp) QueryOrganization() *OrganizationQuery {
	return NewOAuthAppClient(_m.config).QueryOrganization(_m)
}

// QuerySecrets queries the "secrets" edge of the OAuthApp entity.
func (_m *OAuthApp) QuerySecrets() *OAuthAppSecretQuery {
	return NewOAuthAppClient(_m.config).QuerySecrets(_m)
}

// QueryTokens queries the "tokens" edge of the OAuthApp entity.
func (_m *OAuthApp) QueryTokens() *OAuthTokenQuery {
	return NewOAuthAppClient(_m.config).QueryTokens(_m)
}

// QueryAuthCodes queries the "auth_codes" edge of the OAuthApp entity.
func (_m *OAuthApp) QueryAuthCodes() *OAuthAuthCodeQuery {
	return NewOAuthAppClient(_m.config).QueryAuthCodes(_m)
}

// QueryConsents queries the "consents" edge of the OAuthApp entity.
func (_m *OAuthApp) QueryConsents() *OAuthConsentQuery {
	return NewOAuthAppClient(_m.config).QueryConsents(_m)
}

// Update returns a builder for updating this OAuthApp.
// Note that you need to call OAuthApp.Unwrap() before calling this method if this OAuthApp
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthApp) Update() *OAuthAppUpdateOne {
	return NewOAuthAppClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthApp entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthApp) Unwrap() *OAuthApp {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthApp is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthApp) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthApp(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("logo_url=")
	builder.WriteString(_m.LogoURL)
	builder.WriteString(", ")
	builder.WriteString("app_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppType))
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	if v := _m.OrganizationID; v != nil {
		builder.WriteString("organization_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("redirect_uris=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedirectUris))
	builder.WriteString(", ")
	builder.WriteString("allowed_scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedScopes))
	builder.WriteString(", ")
	builder.WriteString("allowed_grants=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedGrants))
	builder.WriteString(", ")
	builder.WriteString("allowed_response_types=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedResponseTypes))
	builder.WriteString(", ")
	builder.WriteString("access_token_ttl=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccessTokenTTL))
	builder.WriteString(", ")
	builder.WriteString("refresh_token_ttl=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshTokenTTL))
	builder.WriteString(", ")
	builder.WriteString("refresh_token_rotation=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshTokenRotation))
	builder.WriteString(", ")
	builder.WriteString("first_party=")
	builder.WriteString(fmt.Sprintf("%v", _m.FirstParty))
	builder.WriteString(", ")
	builder.WriteString("public=")
	builder.WriteString(fmt.Sprintf("%v", _m.Public))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthApps is a parsable slice of OAuthApp.
type OAuthApps []*OAuthApp
