// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/grokify/systemforge/identity/ent/predicate"
	"github.com/grokify/systemforge/identity/ent/principal"
	"github.com/grokify/systemforge/identity/ent/serviceprincipal"
)

// ServicePrincipalUpdate is the builder for updating ServicePrincipal entities.
type ServicePrincipalUpdate struct {
	config
	hooks    []Hook
	mutation *ServicePrincipalMutation
}

// Where appends a list predicates to the ServicePrincipalUpdate builder.
func (_u *ServicePrincipalUpdate) Where(ps ...predicate.ServicePrincipal) *ServicePrincipalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServicePrincipalUpdate) SetUpdatedAt(v time.Time) *ServicePrincipalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServiceType sets the "service_type" field.
func (_u *ServicePrincipalUpdate) SetServiceType(v string) *ServicePrincipalUpdate {
	_u.mutation.SetServiceType(v)
	return _u
}

// SetNillableServiceType sets the "service_type" field if the given value is not nil.
func (_u *ServicePrincipalUpdate) SetNillableServiceType(v *string) *ServicePrincipalUpdate {
	if v != nil {
		_u.SetServiceType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServicePrincipalUpdate) SetDescription(v string) *ServicePrincipalUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServicePrincipalUpdate) SetNillableDescription(v *string) *ServicePrincipalUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServicePrincipalUpdate) ClearDescription() *ServicePrincipalUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ServicePrincipalUpdate) SetCreatedBy(v uuid.UUID) *ServicePrincipalUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ServicePrincipalUpdate) SetNillableCreatedBy(v *uuid.UUID) *ServicePrincipalUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ServicePrincipalUpdate) ClearCreatedBy() *ServicePrincipalUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ServicePrincipalUpdate) SetLastUsedAt(v time.Time) *ServicePrincipalUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ServicePrincipalUpdate) SetNillableLastUsedAt(v *time.Time) *ServicePrincipalUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ServicePrincipalUpdate) ClearLastUsedAt() *ServicePrincipalUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetAllowedIps sets the "allowed_ips" field.
func (_u *ServicePrincipalUpdate) SetAllowedIps(v []string) *ServicePrincipalUpdate {
	_u.mutation.SetAllowedIps(v)
	return _u
}

// AppendAllowedIps appends value to the "allowed_ips" field.
func (_u *ServicePrincipalUpdate) AppendAllowedIps(v []string) *ServicePrincipalUpdate {
	_u.mutation.AppendAllowedIps(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the Principal entity by ID.
func (_u *ServicePrincipalUpdate) SetCreatorID(id uuid.UUID) *ServicePrincipalUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the Principal entity by ID if the given value is not nil.
func (_u *ServicePrincipalUpdate) SetNillableCreatorID(id *uuid.UUID) *ServicePrincipalUpdate {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the Principal entity.
func (_u *ServicePrincipalUpdate) SetCreator(v *Principal) *ServicePrincipalUpdate {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the ServicePrincipalMutation object of the builder.
func (_u *ServicePrincipalUpdate) Mutation() *ServicePrincipalMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the Principal entity.
func (_u *ServicePrincipalUpdate) ClearCreator() *ServicePrincipalUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServicePrincipalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServicePrincipalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServicePrincipalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServicePrincipalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServicePrincipalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serviceprincipal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServicePrincipalUpdate) check() error {
	if v, ok := _u.mutation.ServiceType(); ok {
		if err := serviceprincipal.ServiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "service_type", err: fmt.Errorf(`ent: validator failed for field "ServicePrincipal.service_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := serviceprincipal.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ServicePrincipal.description": %w`, err)}
		}
	}
	if _u.mutation.PrincipalCleared() && len(_u.mutation.PrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipal.principal"`)
	}
	return nil
}

func (_u *ServicePrincipalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceprincipal.Table, serviceprincipal.Columns, sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceprincipal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ServiceType(); ok {
		_spec.SetField(serviceprincipal.FieldServiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(serviceprincipal.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(serviceprincipal.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(serviceprincipal.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(serviceprincipal.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AllowedIps(); ok {
		_spec.SetField(serviceprincipal.FieldAllowedIps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceprincipal.FieldAllowedIps, value)
		})
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipal.CreatorTable,
			Columns: []string{serviceprincipal.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipal.CreatorTable,
			Columns: []string{serviceprincipal.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceprincipal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServicePrincipalUpdateOne is the builder for updating a single ServicePrincipal entity.
type ServicePrincipalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServicePrincipalMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServicePrincipalUpdateOne) SetUpdatedAt(v time.Time) *ServicePrincipalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServiceType sets the "service_type" field.
func (_u *ServicePrincipalUpdateOne) SetServiceType(v string) *ServicePrincipalUpdateOne {
	_u.mutation.SetServiceType(v)
	return _u
}

// SetNillableServiceType sets the "service_type" field if the given value is not nil.
func (_u *ServicePrincipalUpdateOne) SetNillableServiceType(v *string) *ServicePrincipalUpdateOne {
	if v != nil {
		_u.SetServiceType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServicePrincipalUpdateOne) SetDescription(v string) *ServicePrincipalUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServicePrincipalUpdateOne) SetNillableDescription(v *string) *ServicePrincipalUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServicePrincipalUpdateOne) ClearDescription() *ServicePrincipalUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ServicePrincipalUpdateOne) SetCreatedBy(v uuid.UUID) *ServicePrincipalUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ServicePrincipalUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *ServicePrincipalUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ServicePrincipalUpdateOne) ClearCreatedBy() *ServicePrincipalUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ServicePrincipalUpdateOne) SetLastUsedAt(v time.Time) *ServicePrincipalUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ServicePrincipalUpdateOne) SetNillableLastUsedAt(v *time.Time) *ServicePrincipalUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ServicePrincipalUpdateOne) ClearLastUsedAt() *ServicePrincipalUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetAllowedIps sets the "allowed_ips" field.
func (_u *ServicePrincipalUpdateOne) SetAllowedIps(v []string) *ServicePrincipalUpdateOne {
	_u.mutation.SetAllowedIps(v)
	return _u
}

// AppendAllowedIps appends value to the "allowed_ips" field.
func (_u *ServicePrincipalUpdateOne) AppendAllowedIps(v []string) *ServicePrincipalUpdateOne {
	_u.mutation.AppendAllowedIps(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the Principal entity by ID.
func (_u *ServicePrincipalUpdateOne) SetCreatorID(id uuid.UUID) *ServicePrincipalUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the Principal entity by ID if the given value is not nil.
func (_u *ServicePrincipalUpdateOne) SetNillableCreatorID(id *uuid.UUID) *ServicePrincipalUpdateOne {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the Principal entity.
func (_u *ServicePrincipalUpdateOne) SetCreator(v *Principal) *ServicePrincipalUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the ServicePrincipalMutation object of the builder.
func (_u *ServicePrincipalUpdateOne) Mutation() *ServicePrincipalMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the Principal entity.
func (_u *ServicePrincipalUpdateOne) ClearCreator() *ServicePrincipalUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// Where appends a list predicates to the ServicePrincipalUpdate builder.
func (_u *ServicePrincipalUpdateOne) Where(ps ...predicate.ServicePrincipal) *ServicePrincipalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServicePrincipalUpdateOne) Select(field string, fields ...string) *ServicePrincipalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServicePrincipal entity.
func (_u *ServicePrincipalUpdateOne) Save(ctx context.Context) (*ServicePrincipal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServicePrincipalUpdateOne) SaveX(ctx context.Context) *ServicePrincipal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServicePrincipalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServicePrincipalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServicePrincipalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serviceprincipal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServicePrincipalUpdateOne) check() error {
	if v, ok := _u.mutation.ServiceType(); ok {
		if err := serviceprincipal.ServiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "service_type", err: fmt.Errorf(`ent: validator failed for field "ServicePrincipal.service_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := serviceprincipal.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ServicePrincipal.description": %w`, err)}
		}
	}
	if _u.mutation.PrincipalCleared() && len(_u.mutation.PrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipal.principal"`)
	}
	return nil
}

func (_u *ServicePrincipalUpdateOne) sqlSave(ctx context.Context) (_node *ServicePrincipal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceprincipal.Table, serviceprincipal.Columns, sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServicePrincipal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serviceprincipal.FieldID)
		for _, f := range fields {
			if !serviceprincipal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serviceprincipal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceprincipal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ServiceType(); ok {
		_spec.SetField(serviceprincipal.FieldServiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(serviceprincipal.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(serviceprincipal.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(serviceprincipal.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(serviceprincipal.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AllowedIps(); ok {
		_spec.SetField(serviceprincipal.FieldAllowedIps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceprincipal.FieldAllowedIps, value)
		})
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipal.CreatorTable,
			Columns: []string{serviceprincipal.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipal.CreatorTable,
			Columns: []string{serviceprincipal.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ServicePrincipal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceprincipal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
