// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/grokify/systemforge/identity/ent/principal"
	"github.com/grokify/systemforge/identity/ent/serviceprincipal"
)

// ServicePrincipal is the model entity for the ServicePrincipal schema.
type ServicePrincipal struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Reference to parent Principal
	PrincipalID uuid.UUID `json:"principal_id,omitempty"`
	// Type of service (e.g., backend, worker, gateway)
	ServiceType string `json:"service_type,omitempty"`
	// Service description
	Description string `json:"description,omitempty"`
	// Principal who created this service account
	CreatedBy *uuid.UUID `json:"created_by,omitempty"`
	// Last time this service account was used
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// IP addresses/CIDRs allowed to use this service account
	AllowedIps []string `json:"allowed_ips,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServicePrincipalQuery when eager-loading is set.
	Edges        ServicePrincipalEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServicePrincipalEdges holds the relations/edges for other nodes in the graph.
type ServicePrincipalEdges struct {
	// Principal holds the value of the principal edge.
	Principal *Principal `json:"principal,omitempty"`
	// Principal who created this service account
	Creator *Principal `json:"creator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PrincipalOrErr returns the Principal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServicePrincipalEdges) PrincipalOrErr() (*Principal, error) {
	if e.Principal != nil {
		return e.Principal, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: principal.Label}
	}
	return nil, &NotLoadedError{edge: "principal"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServicePrincipalEdges) CreatorOrErr() (*Principal, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: principal.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServicePrincipal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serviceprincipal.FieldCreatedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case serviceprincipal.FieldAllowedIps:
			values[i] = new([]byte)
		case serviceprincipal.FieldServiceType, serviceprincipal.FieldDescription:
			values[i] = new(sql.NullString)
		case serviceprincipal.FieldCreatedAt, serviceprincipal.FieldUpdatedAt, serviceprincipal.FieldLastUsedAt:
			values[i] = new(sql.NullTime)
		case serviceprincipal.FieldID, serviceprincipal.FieldPrincipalID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServicePrincipal fields.
func (_m *ServicePrincipal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serviceprincipal.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case serviceprincipal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case serviceprincipal.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case serviceprincipal.FieldPrincipalID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field principal_id", values[i])
			} else if value != nil {
				_m.PrincipalID = *value
			}
		case serviceprincipal.FieldServiceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_type", values[i])
			} else if value.Valid {
				_m.ServiceType = value.String
			}
		case serviceprincipal.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case serviceprincipal.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uuid.UUID)
				*_m.CreatedBy = *value.S.(*uuid.UUID)
			}
		case serviceprincipal.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case serviceprincipal.FieldAllowedIps:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_ips", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedIps); err != nil {
					return fmt.Errorf("unmarshal field allowed_ips: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServicePrincipal.
// This includes values selected through modifiers, order, etc.
func (_m *ServicePrincipal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPrincipal queries the "principal" edge of the ServicePrincipal entity.
func (_m *ServicePrincipal) QueryPrincipal() *PrincipalQuery {
	return NewServicePrincipalClient(_m.config).QueryPrincipal(_m)
}

// QueryCreator queries the "creator" edge of the ServicePrincipal entity.
func (_m *ServicePrincipal) QueryCreator() *PrincipalQuery {
	return NewServicePrincipalClient(_m.config).QueryCreator(_m)
}

// Update returns a builder for updating this ServicePrincipal.
// Note that you need to call ServicePrincipal.Unwrap() before calling this method if this ServicePrincipal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServicePrincipal) Update() *ServicePrincipalUpdateOne {
	return NewServicePrincipalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServicePrincipal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServicePrincipal) Unwrap() *ServicePrincipal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServicePrincipal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServicePrincipal) String() string {
	var builder strings.Builder
	builder.WriteString("ServicePrincipal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("principal_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrincipalID))
	builder.WriteString(", ")
	builder.WriteString("service_type=")
	builder.WriteString(_m.ServiceType)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("allowed_ips=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedIps))
	builder.WriteByte(')')
	return builder.String()
}

// ServicePrincipals is a parsable slice of ServicePrincipal.
type ServicePrincipals []*ServicePrincipal
