// Code generated by ent, DO NOT EDIT.

package principaltoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/grokify/coreforge/identity/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldID, id))
}

// PrincipalID applies equality check predicate on the "principal_id" field. It's identical to PrincipalIDEQ.
func PrincipalID(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldPrincipalID, v))
}

// IssuedByAppID applies equality check predicate on the "issued_by_app_id" field. It's identical to IssuedByAppIDEQ.
func IssuedByAppID(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldIssuedByAppID, v))
}

// AccessTokenSignature applies equality check predicate on the "access_token_signature" field. It's identical to AccessTokenSignatureEQ.
func AccessTokenSignature(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldAccessTokenSignature, v))
}

// RefreshTokenSignature applies equality check predicate on the "refresh_token_signature" field. It's identical to RefreshTokenSignatureEQ.
func RefreshTokenSignature(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRefreshTokenSignature, v))
}

// FamilyID applies equality check predicate on the "family_id" field. It's identical to FamilyIDEQ.
func FamilyID(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldFamilyID, v))
}

// ParentTokenID applies equality check predicate on the "parent_token_id" field. It's identical to ParentTokenIDEQ.
func ParentTokenID(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldParentTokenID, v))
}

// DpopJkt applies equality check predicate on the "dpop_jkt" field. It's identical to DpopJktEQ.
func DpopJkt(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldDpopJkt, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldSessionID, v))
}

// RequestData applies equality check predicate on the "request_data" field. It's identical to RequestDataEQ.
func RequestData(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRequestData, v))
}

// AccessExpiresAt applies equality check predicate on the "access_expires_at" field. It's identical to AccessExpiresAtEQ.
func AccessExpiresAt(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldAccessExpiresAt, v))
}

// RefreshExpiresAt applies equality check predicate on the "refresh_expires_at" field. It's identical to RefreshExpiresAtEQ.
func RefreshExpiresAt(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRefreshExpiresAt, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRevoked, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedReason applies equality check predicate on the "revoked_reason" field. It's identical to RevokedReasonEQ.
func RevokedReason(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRevokedReason, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldClientIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldUserAgent, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldCreatedAt, v))
}

// PrincipalIDEQ applies the EQ predicate on the "principal_id" field.
func PrincipalIDEQ(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldPrincipalID, v))
}

// PrincipalIDNEQ applies the NEQ predicate on the "principal_id" field.
func PrincipalIDNEQ(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldPrincipalID, v))
}

// PrincipalIDIn applies the In predicate on the "principal_id" field.
func PrincipalIDIn(vs ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldPrincipalID, vs...))
}

// PrincipalIDNotIn applies the NotIn predicate on the "principal_id" field.
func PrincipalIDNotIn(vs ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldPrincipalID, vs...))
}

// PrincipalTypeEQ applies the EQ predicate on the "principal_type" field.
func PrincipalTypeEQ(v PrincipalType) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldPrincipalType, v))
}

// PrincipalTypeNEQ applies the NEQ predicate on the "principal_type" field.
func PrincipalTypeNEQ(v PrincipalType) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldPrincipalType, v))
}

// PrincipalTypeIn applies the In predicate on the "principal_type" field.
func PrincipalTypeIn(vs ...PrincipalType) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldPrincipalType, vs...))
}

// PrincipalTypeNotIn applies the NotIn predicate on the "principal_type" field.
func PrincipalTypeNotIn(vs ...PrincipalType) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldPrincipalType, vs...))
}

// IssuedByAppIDEQ applies the EQ predicate on the "issued_by_app_id" field.
func IssuedByAppIDEQ(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldIssuedByAppID, v))
}

// IssuedByAppIDNEQ applies the NEQ predicate on the "issued_by_app_id" field.
func IssuedByAppIDNEQ(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldIssuedByAppID, v))
}

// IssuedByAppIDIn applies the In predicate on the "issued_by_app_id" field.
func IssuedByAppIDIn(vs ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldIssuedByAppID, vs...))
}

// IssuedByAppIDNotIn applies the NotIn predicate on the "issued_by_app_id" field.
func IssuedByAppIDNotIn(vs ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldIssuedByAppID, vs...))
}

// IssuedByAppIDIsNil applies the IsNil predicate on the "issued_by_app_id" field.
func IssuedByAppIDIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldIssuedByAppID))
}

// IssuedByAppIDNotNil applies the NotNil predicate on the "issued_by_app_id" field.
func IssuedByAppIDNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldIssuedByAppID))
}

// AccessTokenSignatureEQ applies the EQ predicate on the "access_token_signature" field.
func AccessTokenSignatureEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureNEQ applies the NEQ predicate on the "access_token_signature" field.
func AccessTokenSignatureNEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureIn applies the In predicate on the "access_token_signature" field.
func AccessTokenSignatureIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldAccessTokenSignature, vs...))
}

// AccessTokenSignatureNotIn applies the NotIn predicate on the "access_token_signature" field.
func AccessTokenSignatureNotIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldAccessTokenSignature, vs...))
}

// AccessTokenSignatureGT applies the GT predicate on the "access_token_signature" field.
func AccessTokenSignatureGT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureGTE applies the GTE predicate on the "access_token_signature" field.
func AccessTokenSignatureGTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureLT applies the LT predicate on the "access_token_signature" field.
func AccessTokenSignatureLT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureLTE applies the LTE predicate on the "access_token_signature" field.
func AccessTokenSignatureLTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureContains applies the Contains predicate on the "access_token_signature" field.
func AccessTokenSignatureContains(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContains(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureHasPrefix applies the HasPrefix predicate on the "access_token_signature" field.
func AccessTokenSignatureHasPrefix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasPrefix(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureHasSuffix applies the HasSuffix predicate on the "access_token_signature" field.
func AccessTokenSignatureHasSuffix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasSuffix(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureEqualFold applies the EqualFold predicate on the "access_token_signature" field.
func AccessTokenSignatureEqualFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEqualFold(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureContainsFold applies the ContainsFold predicate on the "access_token_signature" field.
func AccessTokenSignatureContainsFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContainsFold(FieldAccessTokenSignature, v))
}

// RefreshTokenSignatureEQ applies the EQ predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureNEQ applies the NEQ predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureNEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureIn applies the In predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldRefreshTokenSignature, vs...))
}

// RefreshTokenSignatureNotIn applies the NotIn predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureNotIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldRefreshTokenSignature, vs...))
}

// RefreshTokenSignatureGT applies the GT predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureGT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureGTE applies the GTE predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureGTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureLT applies the LT predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureLT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureLTE applies the LTE predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureLTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureContains applies the Contains predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureContains(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContains(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureHasPrefix applies the HasPrefix predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureHasPrefix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasPrefix(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureHasSuffix applies the HasSuffix predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureHasSuffix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasSuffix(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureIsNil applies the IsNil predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldRefreshTokenSignature))
}

// RefreshTokenSignatureNotNil applies the NotNil predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldRefreshTokenSignature))
}

// RefreshTokenSignatureEqualFold applies the EqualFold predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureEqualFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEqualFold(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureContainsFold applies the ContainsFold predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureContainsFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContainsFold(FieldRefreshTokenSignature, v))
}

// FamilyIDEQ applies the EQ predicate on the "family_id" field.
func FamilyIDEQ(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldFamilyID, v))
}

// FamilyIDNEQ applies the NEQ predicate on the "family_id" field.
func FamilyIDNEQ(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldFamilyID, v))
}

// FamilyIDIn applies the In predicate on the "family_id" field.
func FamilyIDIn(vs ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldFamilyID, vs...))
}

// FamilyIDNotIn applies the NotIn predicate on the "family_id" field.
func FamilyIDNotIn(vs ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldFamilyID, vs...))
}

// FamilyIDGT applies the GT predicate on the "family_id" field.
func FamilyIDGT(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldFamilyID, v))
}

// FamilyIDGTE applies the GTE predicate on the "family_id" field.
func FamilyIDGTE(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldFamilyID, v))
}

// FamilyIDLT applies the LT predicate on the "family_id" field.
func FamilyIDLT(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldFamilyID, v))
}

// FamilyIDLTE applies the LTE predicate on the "family_id" field.
func FamilyIDLTE(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldFamilyID, v))
}

// ParentTokenIDEQ applies the EQ predicate on the "parent_token_id" field.
func ParentTokenIDEQ(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldParentTokenID, v))
}

// ParentTokenIDNEQ applies the NEQ predicate on the "parent_token_id" field.
func ParentTokenIDNEQ(v uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldParentTokenID, v))
}

// ParentTokenIDIn applies the In predicate on the "parent_token_id" field.
func ParentTokenIDIn(vs ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldParentTokenID, vs...))
}

// ParentTokenIDNotIn applies the NotIn predicate on the "parent_token_id" field.
func ParentTokenIDNotIn(vs ...uuid.UUID) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldParentTokenID, vs...))
}

// ParentTokenIDIsNil applies the IsNil predicate on the "parent_token_id" field.
func ParentTokenIDIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldParentTokenID))
}

// ParentTokenIDNotNil applies the NotNil predicate on the "parent_token_id" field.
func ParentTokenIDNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldParentTokenID))
}

// DpopJktEQ applies the EQ predicate on the "dpop_jkt" field.
func DpopJktEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldDpopJkt, v))
}

// DpopJktNEQ applies the NEQ predicate on the "dpop_jkt" field.
func DpopJktNEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldDpopJkt, v))
}

// DpopJktIn applies the In predicate on the "dpop_jkt" field.
func DpopJktIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldDpopJkt, vs...))
}

// DpopJktNotIn applies the NotIn predicate on the "dpop_jkt" field.
func DpopJktNotIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldDpopJkt, vs...))
}

// DpopJktGT applies the GT predicate on the "dpop_jkt" field.
func DpopJktGT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldDpopJkt, v))
}

// DpopJktGTE applies the GTE predicate on the "dpop_jkt" field.
func DpopJktGTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldDpopJkt, v))
}

// DpopJktLT applies the LT predicate on the "dpop_jkt" field.
func DpopJktLT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldDpopJkt, v))
}

// DpopJktLTE applies the LTE predicate on the "dpop_jkt" field.
func DpopJktLTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldDpopJkt, v))
}

// DpopJktContains applies the Contains predicate on the "dpop_jkt" field.
func DpopJktContains(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContains(FieldDpopJkt, v))
}

// DpopJktHasPrefix applies the HasPrefix predicate on the "dpop_jkt" field.
func DpopJktHasPrefix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasPrefix(FieldDpopJkt, v))
}

// DpopJktHasSuffix applies the HasSuffix predicate on the "dpop_jkt" field.
func DpopJktHasSuffix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasSuffix(FieldDpopJkt, v))
}

// DpopJktIsNil applies the IsNil predicate on the "dpop_jkt" field.
func DpopJktIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldDpopJkt))
}

// DpopJktNotNil applies the NotNil predicate on the "dpop_jkt" field.
func DpopJktNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldDpopJkt))
}

// DpopJktEqualFold applies the EqualFold predicate on the "dpop_jkt" field.
func DpopJktEqualFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEqualFold(FieldDpopJkt, v))
}

// DpopJktContainsFold applies the ContainsFold predicate on the "dpop_jkt" field.
func DpopJktContainsFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContainsFold(FieldDpopJkt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDIsNil applies the IsNil predicate on the "session_id" field.
func SessionIDIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldSessionID))
}

// SessionIDNotNil applies the NotNil predicate on the "session_id" field.
func SessionIDNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldSessionID))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContainsFold(FieldSessionID, v))
}

// RequestDataEQ applies the EQ predicate on the "request_data" field.
func RequestDataEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRequestData, v))
}

// RequestDataNEQ applies the NEQ predicate on the "request_data" field.
func RequestDataNEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldRequestData, v))
}

// RequestDataIn applies the In predicate on the "request_data" field.
func RequestDataIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldRequestData, vs...))
}

// RequestDataNotIn applies the NotIn predicate on the "request_data" field.
func RequestDataNotIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldRequestData, vs...))
}

// RequestDataGT applies the GT predicate on the "request_data" field.
func RequestDataGT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldRequestData, v))
}

// RequestDataGTE applies the GTE predicate on the "request_data" field.
func RequestDataGTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldRequestData, v))
}

// RequestDataLT applies the LT predicate on the "request_data" field.
func RequestDataLT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldRequestData, v))
}

// RequestDataLTE applies the LTE predicate on the "request_data" field.
func RequestDataLTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldRequestData, v))
}

// RequestDataContains applies the Contains predicate on the "request_data" field.
func RequestDataContains(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContains(FieldRequestData, v))
}

// RequestDataHasPrefix applies the HasPrefix predicate on the "request_data" field.
func RequestDataHasPrefix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasPrefix(FieldRequestData, v))
}

// RequestDataHasSuffix applies the HasSuffix predicate on the "request_data" field.
func RequestDataHasSuffix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasSuffix(FieldRequestData, v))
}

// RequestDataIsNil applies the IsNil predicate on the "request_data" field.
func RequestDataIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldRequestData))
}

// RequestDataNotNil applies the NotNil predicate on the "request_data" field.
func RequestDataNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldRequestData))
}

// RequestDataEqualFold applies the EqualFold predicate on the "request_data" field.
func RequestDataEqualFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEqualFold(FieldRequestData, v))
}

// RequestDataContainsFold applies the ContainsFold predicate on the "request_data" field.
func RequestDataContainsFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContainsFold(FieldRequestData, v))
}

// AccessExpiresAtEQ applies the EQ predicate on the "access_expires_at" field.
func AccessExpiresAtEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldAccessExpiresAt, v))
}

// AccessExpiresAtNEQ applies the NEQ predicate on the "access_expires_at" field.
func AccessExpiresAtNEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldAccessExpiresAt, v))
}

// AccessExpiresAtIn applies the In predicate on the "access_expires_at" field.
func AccessExpiresAtIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldAccessExpiresAt, vs...))
}

// AccessExpiresAtNotIn applies the NotIn predicate on the "access_expires_at" field.
func AccessExpiresAtNotIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldAccessExpiresAt, vs...))
}

// AccessExpiresAtGT applies the GT predicate on the "access_expires_at" field.
func AccessExpiresAtGT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldAccessExpiresAt, v))
}

// AccessExpiresAtGTE applies the GTE predicate on the "access_expires_at" field.
func AccessExpiresAtGTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldAccessExpiresAt, v))
}

// AccessExpiresAtLT applies the LT predicate on the "access_expires_at" field.
func AccessExpiresAtLT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldAccessExpiresAt, v))
}

// AccessExpiresAtLTE applies the LTE predicate on the "access_expires_at" field.
func AccessExpiresAtLTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldAccessExpiresAt, v))
}

// RefreshExpiresAtEQ applies the EQ predicate on the "refresh_expires_at" field.
func RefreshExpiresAtEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtNEQ applies the NEQ predicate on the "refresh_expires_at" field.
func RefreshExpiresAtNEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtIn applies the In predicate on the "refresh_expires_at" field.
func RefreshExpiresAtIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldRefreshExpiresAt, vs...))
}

// RefreshExpiresAtNotIn applies the NotIn predicate on the "refresh_expires_at" field.
func RefreshExpiresAtNotIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldRefreshExpiresAt, vs...))
}

// RefreshExpiresAtGT applies the GT predicate on the "refresh_expires_at" field.
func RefreshExpiresAtGT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtGTE applies the GTE predicate on the "refresh_expires_at" field.
func RefreshExpiresAtGTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtLT applies the LT predicate on the "refresh_expires_at" field.
func RefreshExpiresAtLT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtLTE applies the LTE predicate on the "refresh_expires_at" field.
func RefreshExpiresAtLTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtIsNil applies the IsNil predicate on the "refresh_expires_at" field.
func RefreshExpiresAtIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldRefreshExpiresAt))
}

// RefreshExpiresAtNotNil applies the NotNil predicate on the "refresh_expires_at" field.
func RefreshExpiresAtNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldRefreshExpiresAt))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldRevoked, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldRevokedAt))
}

// RevokedReasonEQ applies the EQ predicate on the "revoked_reason" field.
func RevokedReasonEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldRevokedReason, v))
}

// RevokedReasonNEQ applies the NEQ predicate on the "revoked_reason" field.
func RevokedReasonNEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldRevokedReason, v))
}

// RevokedReasonIn applies the In predicate on the "revoked_reason" field.
func RevokedReasonIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldRevokedReason, vs...))
}

// RevokedReasonNotIn applies the NotIn predicate on the "revoked_reason" field.
func RevokedReasonNotIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldRevokedReason, vs...))
}

// RevokedReasonGT applies the GT predicate on the "revoked_reason" field.
func RevokedReasonGT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldRevokedReason, v))
}

// RevokedReasonGTE applies the GTE predicate on the "revoked_reason" field.
func RevokedReasonGTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldRevokedReason, v))
}

// RevokedReasonLT applies the LT predicate on the "revoked_reason" field.
func RevokedReasonLT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldRevokedReason, v))
}

// RevokedReasonLTE applies the LTE predicate on the "revoked_reason" field.
func RevokedReasonLTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldRevokedReason, v))
}

// RevokedReasonContains applies the Contains predicate on the "revoked_reason" field.
func RevokedReasonContains(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContains(FieldRevokedReason, v))
}

// RevokedReasonHasPrefix applies the HasPrefix predicate on the "revoked_reason" field.
func RevokedReasonHasPrefix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasPrefix(FieldRevokedReason, v))
}

// RevokedReasonHasSuffix applies the HasSuffix predicate on the "revoked_reason" field.
func RevokedReasonHasSuffix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasSuffix(FieldRevokedReason, v))
}

// RevokedReasonIsNil applies the IsNil predicate on the "revoked_reason" field.
func RevokedReasonIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldRevokedReason))
}

// RevokedReasonNotNil applies the NotNil predicate on the "revoked_reason" field.
func RevokedReasonNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldRevokedReason))
}

// RevokedReasonEqualFold applies the EqualFold predicate on the "revoked_reason" field.
func RevokedReasonEqualFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEqualFold(FieldRevokedReason, v))
}

// RevokedReasonContainsFold applies the ContainsFold predicate on the "revoked_reason" field.
func RevokedReasonContainsFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContainsFold(FieldRevokedReason, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPIsNil applies the IsNil predicate on the "client_ip" field.
func ClientIPIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldClientIP))
}

// ClientIPNotNil applies the NotNil predicate on the "client_ip" field.
func ClientIPNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldClientIP))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContainsFold(FieldClientIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldContainsFold(FieldUserAgent, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotNull(FieldLastUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPrincipal applies the HasEdge predicate on the "principal" edge.
func HasPrincipal() predicate.PrincipalToken {
	return predicate.PrincipalToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PrincipalTable, PrincipalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrincipalWith applies the HasEdge predicate on the "principal" edge with a given conditions (other predicates).
func HasPrincipalWith(preds ...predicate.Principal) predicate.PrincipalToken {
	return predicate.PrincipalToken(func(s *sql.Selector) {
		step := newPrincipalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIssuedByApp applies the HasEdge predicate on the "issued_by_app" edge.
func HasIssuedByApp() predicate.PrincipalToken {
	return predicate.PrincipalToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IssuedByAppTable, IssuedByAppColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIssuedByAppWith applies the HasEdge predicate on the "issued_by_app" edge with a given conditions (other predicates).
func HasIssuedByAppWith(preds ...predicate.Application) predicate.PrincipalToken {
	return predicate.PrincipalToken(func(s *sql.Selector) {
		step := newIssuedByAppStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParentToken applies the HasEdge predicate on the "parent_token" edge.
func HasParentToken() predicate.PrincipalToken {
	return predicate.PrincipalToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTokenTable, ParentTokenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentTokenWith applies the HasEdge predicate on the "parent_token" edge with a given conditions (other predicates).
func HasParentTokenWith(preds ...predicate.PrincipalToken) predicate.PrincipalToken {
	return predicate.PrincipalToken(func(s *sql.Selector) {
		step := newParentTokenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildTokens applies the HasEdge predicate on the "child_tokens" edge.
func HasChildTokens() predicate.PrincipalToken {
	return predicate.PrincipalToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildTokensTable, ChildTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildTokensWith applies the HasEdge predicate on the "child_tokens" edge with a given conditions (other predicates).
func HasChildTokensWith(preds ...predicate.PrincipalToken) predicate.PrincipalToken {
	return predicate.PrincipalToken(func(s *sql.Selector) {
		step := newChildTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PrincipalToken) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PrincipalToken) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PrincipalToken) predicate.PrincipalToken {
	return predicate.PrincipalToken(sql.NotPredicates(p))
}
